import { MuralProjectWithTranslation } from './types';

// Comprehensive portfolio dataset with all artworks
export const categoryLabels: Record<'all' | 'murals' | 'budhaood' | 'freemind' | 'landscapes' | 'canvas' | 'details', { en: string; es: string }> = {
  all: { en: 'All Works', es: 'Todas las Obras' },
  murals: { en: 'Murals', es: 'Murales' },
  budhaood: { en: 'Budhaood Series', es: 'Serie Budhaood' },
  freemind: { en: 'Free Mind Series', es: 'Serie Mente Libre' },
  landscapes: { en: 'Future Landscapes', es: 'Paisajes Futuros' },
  canvas: { en: 'Canvas Works', es: 'Obras en Lienzo' },
  details: { en: 'Detail Views', es: 'Vistas Detalladas' },
};

export const portfolioArtworks: MuralProjectWithTranslation[] = [
  {
    id: 'wynwood-mural',
    title: 'Wynwood Walls',
    titleEs: 'Paredes de Wynwood',
    description: 'A stunning large-scale mural in Miami\'s iconic Wynwood Arts District, showcasing vibrant colors and dynamic street art composition that captures the energy of urban creativity.',
    descriptionEs: 'Un impresionante mural a gran escala en el icónico Distrito de Artes de Wynwood en Miami, mostrando colores vibrantes y composición dinámica de arte callejero que captura la energía de la creatividad urbana.',
    location: '',
    year: 2023,
    width: 45,
    height: 25,
    medium: 'Acrylic and spray paint on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Wynwood-Fiorella-Podesta-GOPR9081.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Wynwood Walls',
    translatedDescription: 'A stunning large-scale mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01')
  },
  {
    id: 'soy-mis-suenos',
    title: 'Soy Mis Sueños',
    titleEs: 'Soy Mis Sueños',
    description: 'An empowering mural declaring "I am my dreams" - a powerful statement piece celebrating personal aspirations and the courage to pursue one\'s vision through vibrant artistic expression.',
    descriptionEs: 'Un mural empoderador declarando "Soy mis sueños" - una pieza de declaración poderosa celebrando aspiraciones personales y el coraje de perseguir la visión propia a través de expresión artística vibrante.',
    location: '',
    year: 2022,
    width: 38,
    height: 20,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/soy mis sueños.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Soy Mis Sueños',
    translatedDescription: 'An empowering mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01')
  },
  {
    id: 'montessori-academy-2023',
    title: 'Montessori Academy Garden Mural',
    titleEs: 'Mural del Jardín de la Academia Montessori',
    description: 'A whimsical and educational mural designed for young learners, featuring nature-inspired imagery and vibrant botanical elements that create an engaging outdoor learning environment.',
    descriptionEs: 'Un mural caprichoso y educativo diseñado para jóvenes aprendices, con imágenes inspiradas en la naturaleza y elementos botánicos vibrantes que crean un entorno de aprendizaje al aire libre atractivo.',
    location: '',
    year: 2023,
    width: 32,
    height: 18,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Montessori Academy garden mural 2023.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Montessori Academy Garden Mural',
    translatedDescription: 'A whimsical and educational...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2023-06-01')
  },
  {
    id: 'montessori-academy-2',
    title: 'Montessori Academy Interior Mural',
    titleEs: 'Mural Interior de la Academia Montessori',
    description: 'A colorful educational mural bringing learning to life through artistic storytelling, featuring playful characters and educational themes that inspire curiosity and creativity in students.',
    descriptionEs: 'Un mural educativo colorido que da vida al aprendizaje a través de narrativa artística, con personajes lúdicos y temas educativos que inspiran curiosidad y creatividad en los estudiantes.',
    location: '',
    year: 2023,
    width: 35,
    height: 16,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Montessori Academy Mural 2  .JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Montessori Academy Interior Mural',
    translatedDescription: 'A colorful educational mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-05-01'),
    updatedAt: new Date('2023-05-01')
  },
  {
    id: 'coral-gables-school',
    title: 'Coral Gables School Mural',
    titleEs: 'Mural de la Escuela de Coral Gables',
    description: 'An inspiring educational mural that transforms school spaces into vibrant learning environments, combining artistic excellence with educational themes to engage and motivate students.',
    descriptionEs: 'Un mural educativo inspirador que transforma espacios escolares en entornos de aprendizaje vibrantes, combinando excelencia artística con temas educativos para involucrar y motivar a los estudiantes.',
    location: '',
    year: 2022,
    width: 40,
    height: 20,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Coral Gables School Mural .JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Coral Gables School Mural',
    translatedDescription: 'An inspiring educational mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-08-01'),
    updatedAt: new Date('2022-08-01')
  },
  {
    id: 'coral-gables-school-2',
    title: 'Coral Gables School - Detail View',
    titleEs: 'Escuela de Coral Gables - Vista Detallada',
    description: 'A detailed perspective of the Coral Gables school installation, showcasing the intricate brushwork and vibrant color palette that brings educational spaces to life through art.',
    descriptionEs: 'Una perspectiva detallada de la instalación de la escuela de Coral Gables, mostrando el pincel intrincado y paleta de colores vibrantes que da vida a espacios educativos a través del arte.',
    location: '',
    year: 2022,
    width: 40,
    height: 20,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Coral Gables School 2.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Coral Gables School - Detail View',
    translatedDescription: 'A detailed perspective...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2022-08-15')
  },
  {
    id: 'boys-girls-delray-gym',
    title: 'Boys & Girls Club Delray - Gym Mural',
    titleEs: 'Club de Niños y Niñas Delray - Mural del Gimnasio',
    description: 'An energetic mural designed to inspire physical activity and teamwork, featuring dynamic sports imagery and motivational themes that energize the athletic space.',
    descriptionEs: 'Un mural energético diseñado para inspirar actividad física y trabajo en equipo, con imágenes deportivas dinámicas y temas motivacionales que energizan el espacio atlético.',
    location: '',
    year: 2023,
    width: 42,
    height: 18,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Delray Boys & Girls Gym mural detal 1.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Boys & Girls Club Delray - Gym Mural',
    translatedDescription: 'An energetic mural designed...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-04-01'),
    updatedAt: new Date('2023-04-01')
  },
  {
    id: 'boys-girls-delray-science',
    title: 'Boys & Girls Club Delray - Science Room',
    titleEs: 'Club de Niños y Niñas Delray - Sala de Ciencias',
    description: 'An educational mural celebrating science and discovery, featuring cosmic imagery and scientific themes that inspire curiosity and wonder in young minds exploring STEM subjects.',
    descriptionEs: 'Un mural educativo celebrando ciencia y descubrimiento, con imágenes cósmicas y temas científicos que inspiran curiosidad y asombro en mentes jóvenes explorando temas STEM.',
    location: '',
    year: 2023,
    width: 36,
    height: 16,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Boys & Girls Delray Science room .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Boys & Girls Club Delray - Science Room',
    translatedDescription: 'An educational mural celebrating...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2023-03-01')
  },
  {
    id: 'burst-your-bubble',
    title: 'Burst Your Bubble and Smog',
    titleEs: 'Rompe tu Burbuja y Smog',
    description: 'A thought-provoking environmental statement piece addressing air quality and urban pollution through powerful imagery that challenges viewers to consider their impact on the planet.',
    descriptionEs: 'Una pieza de declaración ambiental que provoca reflexión sobre calidad del aire y contaminación urbana a través de imágenes poderosas que desafían a los espectadores a considerar su impacto en el planeta.',
    location: '',
    year: 2021,
    width: 34,
    height: 17,
    medium: 'Acrylic and spray paint on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Burst your bubble and smog1.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Burst Your Bubble and Smog',
    translatedDescription: 'A thought-provoking environmental...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2021-09-01'),
    updatedAt: new Date('2021-09-01')
  },
  {
    id: 'la-italiana',
    title: 'La Italiana',
    titleEs: 'La Italiana',
    description: 'A stunning portrait mural celebrating Italian heritage and feminine beauty, featuring intricate details and masterful portraiture that captures timeless elegance on an architectural scale.',
    descriptionEs: 'Un impresionante mural de retrato celebrando herencia italiana y belleza femenina, con detalles intrincados y retrato magistral que captura elegancia atemporal a escala arquitectónica.',
    location: '',
    year: 2022,
    width: 30,
    height: 22,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/La Italiana.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'La Italiana',
    translatedDescription: 'A stunning portrait mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-05-01'),
    updatedAt: new Date('2022-05-01')
  },
  {
    id: 'levito-con-cuarzo',
    title: 'Levito con Cuarzo',
    titleEs: 'Levito con Cuarzo',
    description: 'A mystical mural exploring themes of levitation and crystal energy, blending spiritual symbolism with contemporary street art aesthetics in a mesmerizing composition.',
    descriptionEs: 'Un mural místico explorando temas de levitación y energía cristalina, mezclando simbolismo espiritual con estética de arte callejero contemporáneo en una composición fascinante.',
    location: '',
    year: 2021,
    width: 32,
    height: 18,
    medium: 'Mixed media on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Levito con cuarzo.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Levito con Cuarzo',
    translatedDescription: 'A mystical mural exploring...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2021-07-01'),
    updatedAt: new Date('2021-07-01')
  },
  {
    id: 'in-my-dreams-spain',
    title: 'In My Dreams - Spain',
    titleEs: 'En Mis Sueños - España',
    description: 'A dreamlike mural created during residency in Spain, capturing the romantic essence and architectural beauty of Spanish culture through vibrant colors and surreal imagery.',
    descriptionEs: 'Un mural onírico creado durante residencia en España, capturando la esencia romántica y belleza arquitectónica de la cultura española a través de colores vibrantes e imágenes surrealistas.',
    location: '',
    year: 2019,
    width: 36,
    height: 19,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/Im my dreams front Spain.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'In My Dreams - Spain',
    translatedDescription: 'A dreamlike mural created...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2019-08-01'),
    updatedAt: new Date('2019-08-01')
  },
  {
    id: 'mural-portfolio-03',
    title: 'Colorful Expression',
    titleEs: 'Expresión Colorida',
    description: 'A vibrant outdoor mural bursting with color and life, transforming public spaces into artistic landmarks that celebrate creativity and community through bold visual storytelling.',
    descriptionEs: 'Un mural al aire libre vibrante rebosante de color y vida, transformando espacios públicos en hitos artísticos que celebran creatividad y comunidad a través de narrativa visual audaz.',
    location: '',
    year: 2022,
    width: 38,
    height: 20,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/portfolio_03_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Colorful Expression',
    translatedDescription: 'A vibrant outdoor mural...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-06-01'),
    updatedAt: new Date('2022-06-01')
  },
  {
    id: 'mural-portfolio-05',
    title: 'Urban Canvas',
    titleEs: 'Lienzo Urbano',
    description: 'A contemporary street art mural that transforms urban architecture into a canvas for creative expression, featuring modern aesthetics and bold graphic elements.',
    descriptionEs: 'Un mural de arte callejero contemporáneo que transforma arquitectura urbana en un lienzo para expresión creativa, con estética moderna y elementos gráficos audaces.',
    location: '',
    year: 2022,
    width: 40,
    height: 18,
    medium: 'Spray paint and acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/portfolio_05_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Urban Canvas',
    translatedDescription: 'A contemporary street art...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2022-04-01'),
    updatedAt: new Date('2022-04-01')
  },
  {
    id: 'mural-portfolio-06',
    title: 'Artistic Revolution',
    titleEs: 'Revolución Artística',
    description: 'A powerful mural making a statement through art, combining street culture with fine art techniques to create a visually stunning piece that commands attention and inspires dialogue.',
    descriptionEs: 'Un mural poderoso haciendo una declaración a través del arte, combinando cultura callejera con técnicas de bellas artes para crear una pieza visualmente impresionante que comanda atención e inspira diálogo.',
    location: '',
    year: 2021,
    width: 35,
    height: 19,
    medium: 'Mixed media on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/portfolio_06_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Artistic Revolution',
    translatedDescription: 'A powerful mural making...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2021-10-01'),
    updatedAt: new Date('2021-10-01')
  },
  {
    id: 'mural-portfolio-07',
    title: 'Street Dreams',
    titleEs: 'Sueños Callejeros',
    description: 'An expressive mural capturing the dreams and aspirations of urban communities, blending realism with abstract elements to create a compelling narrative on city walls.',
    descriptionEs: 'Un mural expresivo capturando los sueños y aspiraciones de comunidades urbanas, mezclando realismo con elementos abstractos para crear una narrativa convincente en paredes de la ciudad.',
    location: '',
    year: 2021,
    width: 33,
    height: 17,
    medium: 'Acrylic on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/portfolio_07_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Street Dreams',
    translatedDescription: 'An expressive mural capturing...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2021-05-01'),
    updatedAt: new Date('2021-05-01')
  },
  {
    id: 'mural-hero',
    title: 'Hero Mural',
    titleEs: 'Mural Heroico',
    description: 'A monumental mural celebrating heroes in our communities, featuring powerful imagery and inspirational themes that uplift and unite neighborhoods through public art.',
    descriptionEs: 'Un mural monumental celebrando héroes en nuestras comunidades, con imágenes poderosas y temas inspiradores que elevan y unen vecindarios a través del arte público.',
    location: '',
    year: 2023,
    width: 50,
    height: 25,
    medium: 'Acrylic and spray paint on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/hero_01_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Hero Mural',
    translatedDescription: 'A monumental mural celebrating...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-07-01'),
    updatedAt: new Date('2023-07-01')
  },
  {
    id: 'mural-featured',
    title: 'Featured Wall Art',
    titleEs: 'Arte Mural Destacado',
    description: 'A showcase piece demonstrating mastery of large-scale mural techniques, featuring intricate details and commanding presence that transforms architectural surfaces into works of art.',
    descriptionEs: 'Una pieza de exhibición demostrando maestría de técnicas de mural a gran escala, con detalles intrincados y presencia imponente que transforma superficies arquitectónicas en obras de arte.',
    location: '',
    year: 2023,
    width: 42,
    height: 22,
    medium: 'Mixed media on wall',
    client: '',
    category: 'Murals',
    imageUrl: '/images/Portfolio/Murals/featured_02_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Featured Wall Art',
    translatedDescription: 'A showcase piece demonstrating...',
    dimensions: 'Large-scale mural',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-09-01')
  },

  // CANVAS WORKS - Gallery paintings and studio art
  {
    id: 'portfolio-01',
    title: 'Vibrant Urban Expression',
    titleEs: 'Expresión Urbana Vibrante',
    description: 'A dynamic large-scale mural showcasing bold colors and contemporary street art aesthetics, transforming urban spaces into vibrant artistic landmarks.',
    descriptionEs: 'Un mural dinámico a gran escala que exhibe colores audaces y estética de arte callejero contemporáneo, transformando espacios urbanos en hitos artísticos vibrantes.',
    location: '',
    year: 2023,
    width: 35,
    height: 20,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/budhaood-series/portfolio_01_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Vibrant Urban Expression',
    translatedDescription: 'A dynamic large-scale mural...',
    dimensions: '35 ft × 20 ft',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01')
  },
  {
    id: 'portfolio-02',
    title: 'Abstract Harmony',
    titleEs: 'Armonía Abstracta',
    description: 'Flowing abstract forms merge with vibrant color palettes, creating a mesmerizing visual journey that captures movement and emotion on an architectural canvas.',
    descriptionEs: 'Formas abstractas fluidas se fusionan con paletas de colores vibrantes, creando un viaje visual fascinante que captura movimiento y emoción en un lienzo arquitectónico.',
    location: '',
    year: 2023,
    width: 40,
    height: 18,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/free-mind-series/portfolio_02_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Abstract Harmony',
    translatedDescription: 'Flowing abstract forms...',
    dimensions: '40 ft × 18 ft',
    createdAt: new Date('2023-02-01'),
    updatedAt: new Date('2023-02-01')
  },
  {
    id: 'portfolio-04',
    title: 'Spiritual Awakening',
    titleEs: 'Despertar Espiritual',
    description: 'A meditative mural featuring sacred geometry and spiritual symbolism, blending traditional iconography with contemporary artistic expression to create a peaceful sanctuary.',
    descriptionEs: 'Un mural meditativo con geometría sagrada y simbolismo espiritual, fusionando iconografía tradicional con expresión artística contemporánea para crear un santuario pacífico.',
    location: '',
    year: 2023,
    width: 30,
    height: 16,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/portfolio_04_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Spiritual Awakening',
    translatedDescription: 'A meditative mural...',
    dimensions: '30 ft × 16 ft',
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2023-03-01')
  },

  {
    id: 'portfolio-09',
    title: 'Nature\'s Symphony',
    titleEs: 'Sinfonía de la Naturaleza',
    description: 'A breathtaking botanical composition featuring oversized flora and fauna elements, bringing the beauty and vitality of nature into urban environments with stunning realism.',
    descriptionEs: 'Una composición botánica impresionante con elementos de flora y fauna de gran tamaño, llevando la belleza y vitalidad de la naturaleza a entornos urbanos con realismo impresionante.',
    location: '',
    year: 2022,
    width: 32,
    height: 15,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/free-mind-series/portfolio_09_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Nature\'s Symphony',
    translatedDescription: 'A breathtaking botanical...',
    dimensions: '32 ft × 15 ft',
    createdAt: new Date('2022-02-01'),
    updatedAt: new Date('2022-02-01')
  },

  {
    id: 'shop-03',
    title: 'Urban Poetry',
    titleEs: 'Poesía Urbana',
    description: 'Street art meets fine art in this captivating mural that transforms everyday urban walls into canvases of poetic expression and social commentary.',
    descriptionEs: 'El arte callejero se encuentra con el arte fino en este mural cautivador que transforma las paredes urbanas cotidianas en lienzos de expresión poética y comentario social.',
    location: '',
    year: 2022,
    width: 33,
    height: 16,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/shop_03_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Urban Poetry',
    translatedDescription: 'Street art meets...',
    dimensions: '33 ft × 16 ft',
    createdAt: new Date('2022-03-01'),
    updatedAt: new Date('2022-03-01')
  },
  {
    id: 'shop-07',
    title: 'Chromatic Dreams',
    titleEs: 'Sueños Cromáticos',
    description: 'A mesmerizing display of color theory and artistic mastery, where complementary hues dance across architectural surfaces creating dreamlike atmospheres.',
    descriptionEs: 'Una exhibición fascinante de teoría del color y maestría artística, donde tonos complementarios bailan a través de superficies arquitectónicas creando atmósferas oníricas.',
    location: '',
    year: 2022,
    width: 29,
    height: 13,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/shop_07_cdn_shop_files.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Chromatic Dreams',
    translatedDescription: 'A mesmerizing display...',
    dimensions: '29 ft × 13 ft',
    createdAt: new Date('2022-04-01'),
    updatedAt: new Date('2022-04-01')
  },

  
  // CANVAS WORKS - Gallery paintings and studio art
  {
    id: 'akasha-frog',
    title: 'Akasha Frog',
    titleEs: 'Rana Akasha',
    description: 'A mystical representation merging spiritual symbolism with natural forms, where the frog becomes a vessel for cosmic consciousness and elemental wisdom.',
    descriptionEs: 'Una representación mística que fusiona simbolismo espiritual con formas naturales, donde la rana se convierte en un recipiente de conciencia cósmica y sabiduría elemental.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Akasha Frog.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Akasha Frog',
    translatedDescription: 'A mystical representation...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-05-01'),
    updatedAt: new Date('2023-05-01')
  },
  {
    id: 'arlequina',
    title: 'Arlequina',
    titleEs: 'Arlequina',
    description: 'A vibrant tribute to the harlequin archetype, blending whimsy with depth through bold patterns, theatrical composition, and emotionally charged color choices.',
    descriptionEs: 'Un tributo vibrante al arquetipo del arlequín, mezclando capricho con profundidad a través de patrones audaces, composición teatral y elecciones de color emocionalmente cargadas.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/ARLEQUINA .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Arlequina',
    translatedDescription: 'A vibrant tribute...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2023-06-01')
  },
  {
    id: 'bicicleta',
    title: 'Bicicleta',
    titleEs: 'Bicicleta',
    description: 'A nostalgic celebration of urban mobility and freedom, transforming the humble bicycle into a symbol of sustainable living and artistic expression.',
    descriptionEs: 'Una celebración nostálgica de movilidad urbana y libertad, transformando la humilde bicicleta en un símbolo de vida sostenible y expresión artística.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Bicicleta.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Bicicleta',
    translatedDescription: 'A nostalgic celebration...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-07-01'),
    updatedAt: new Date('2023-07-01')
  },
  {
    id: 'buddha-verde',
    title: 'Green Buddha',
    titleEs: 'Buda Verde',
    description: 'A serene meditation on spiritual enlightenment rendered in healing green tones, embodying tranquility, growth, and the harmonious balance of nature and consciousness.',
    descriptionEs: 'Una meditación serena sobre la iluminación espiritual representada en tonos verdes curativos, encarnando tranquilidad, crecimiento y el equilibrio armonioso de naturaleza y conciencia.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Buddha Verde.jpeg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Green Buddha',
    translatedDescription: 'A serene meditation...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2023-08-01')
  },
  {
    id: 'cachuna',
    title: 'Cachuna',
    titleEs: 'Cachuna',
    description: 'An evocative piece exploring cultural identity through bold imagery and symbolic representation, bridging traditional narratives with contemporary visual language.',
    descriptionEs: 'Una pieza evocadora que explora identidad cultural a través de imágenes audaces y representación simbólica, uniendo narrativas tradicionales con lenguaje visual contemporáneo.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/CACHUNA.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Cachuna',
    translatedDescription: 'An evocative piece...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-05-01'),
    updatedAt: new Date('2022-05-01')
  },
  {
    id: 'dharma-wheel',
    title: 'Dharma Wheel',
    titleEs: 'Rueda del Dharma',
    description: 'A sacred Buddhist symbol reimagined through contemporary artistic vision, representing the path to enlightenment with intricate geometric precision and spiritual depth.',
    descriptionEs: 'Un símbolo budista sagrado reimaginado a través de visión artística contemporánea, representando el camino hacia la iluminación con intrincada precisión geométrica y profundidad espiritual.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Dharma Wheel.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Dharma Wheel',
    translatedDescription: 'A sacred Buddhist symbol...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-09-01')
  },
  {
    id: 'earth-free-mind',
    title: 'Earth - Free Mind Series',
    titleEs: 'Tierra - Serie Mente Libre',
    description: 'Part of the Free Mind series, this piece celebrates our planet through abstract interpretation, encouraging environmental awareness and spiritual connection to Earth.',
    descriptionEs: 'Parte de la serie Mente Libre, esta pieza celebra nuestro planeta a través de interpretación abstracta, fomentando conciencia ambiental y conexión espiritual con la Tierra.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Digital art on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Earth from Free mind by fio.png',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Earth - Free Mind Series',
    translatedDescription: 'Part of the Free Mind series...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2023-10-01')
  },
  {
    id: 'elquiazul',
    title: 'Elqui Azul',
    titleEs: 'Elqui Azul',
    description: 'Inspired by the celestial beauty of Chile\'s Elqui Valley, this artwork captures the mystical blue essence of starlit skies and sacred landscapes.',
    descriptionEs: 'Inspirada en la belleza celestial del Valle de Elqui de Chile, esta obra captura la esencia azul mística de cielos estrellados y paisajes sagrados.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/ELQUIAZUL.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Elqui Azul',
    translatedDescription: 'Inspired by the celestial...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-06-01'),
    updatedAt: new Date('2022-06-01')
  },
  {
    id: 'fire-free-mind',
    title: 'Fire - Free Mind Series',
    titleEs: 'Fuego - Serie Mente Libre',
    description: 'From the Free Mind series, a passionate exploration of transformation and energy through the primal element of fire, symbolizing creative power and spiritual purification.',
    descriptionEs: 'De la serie Mente Libre, una exploración apasionada de transformación y energía a través del elemento primordial del fuego, simbolizando poder creativo y purificación espiritual.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Digital art on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Fire free mind series.png',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Fire - Free Mind Series',
    translatedDescription: 'From the Free Mind series...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-11-01')
  },
  {
    id: 'flowers-talk-b',
    title: 'Flowers Talk',
    titleEs: 'Las Flores Hablan',
    description: 'A botanical conversation rendered in vivid detail, where each bloom speaks its own language of color, form, and natural beauty in harmonious dialogue.',
    descriptionEs: 'Una conversación botánica representada en detalle vívido, donde cada flor habla su propio lenguaje de color, forma y belleza natural en diálogo armonioso.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/FLOWERS TALK B.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Flowers Talk',
    translatedDescription: 'A botanical conversation...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2023-12-01')
  },
  {
    id: 'green-love',
    title: 'Green Love',
    titleEs: 'Amor Verde',
    description: 'An ode to nature and environmental consciousness, expressing love for our planet through lush green palettes and organic, life-affirming compositions.',
    descriptionEs: 'Una oda a la naturaleza y conciencia ambiental, expresando amor por nuestro planeta a través de paletas verdes exuberantes y composiciones orgánicas que afirman la vida.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Green Love.jpeg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Green Love',
    translatedDescription: 'An ode to nature...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-07-01'),
    updatedAt: new Date('2022-07-01')
  },
  {
    id: 'hermanos',
    title: 'Hermanos',
    titleEs: 'Hermanos',
    description: 'A powerful exploration of brotherhood, unity, and shared human experience, depicting connection and solidarity through symbolic imagery and emotional resonance.',
    descriptionEs: 'Una exploración poderosa de hermandad, unidad y experiencia humana compartida, representando conexión y solidaridad a través de imágenes simbólicas y resonancia emocional.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Hermanos.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Hermanos',
    translatedDescription: 'A powerful exploration...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-08-01'),
    updatedAt: new Date('2022-08-01')
  },
  {
    id: 'inhale',
    title: 'Inhale',
    titleEs: 'Inhalar',
    description: 'A meditative piece encouraging mindful breathing and presence, visualizing the life-giving act of inhalation through flowing forms and calming color harmonies.',
    descriptionEs: 'Una pieza meditativa que fomenta respiración consciente y presencia, visualizando el acto vivificante de inhalación a través de formas fluidas y armonías de colores calmantes.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Inhale.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Inhale',
    translatedDescription: 'A meditative piece...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15')
  },
  {
    id: 'la-barca-olga',
    title: 'La Barca de Olga',
    titleEs: 'La Barca de Olga',
    description: 'A narrative painting telling the story of Olga\'s boat, weaving personal history with maritime imagery in a touching tribute to journeys both literal and metaphorical.',
    descriptionEs: 'Una pintura narrativa contando la historia de la barca de Olga, tejiendo historia personal con imágenes marítimas en un tributo conmovedor a viajes tanto literales como metafóricos.',
    location: '',
    year: 2021,
    width: 0,
    height: 0,
    medium: 'Oil on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/La Barca Olga.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'La Barca de Olga',
    translatedDescription: 'A narrative painting...',
    dimensions: 'Canvas',
    createdAt: new Date('2021-05-01'),
    updatedAt: new Date('2021-05-01')
  },
  {
    id: 'lotusy',
    title: 'Lotusy',
    titleEs: 'Lotusy',
    description: 'The sacred lotus reimagined with contemporary flair, symbolizing purity, enlightenment, and rebirth through delicate petals and spiritual significance.',
    descriptionEs: 'El loto sagrado reimaginado con estilo contemporáneo, simbolizando pureza, iluminación y renacimiento a través de pétalos delicados y significado espiritual.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/LOTUSY.Gfinal..jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Lotusy',
    translatedDescription: 'The sacred lotus...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-15')
  },
  {
    id: 'malabar',
    title: 'Malabar',
    titleEs: 'Malabar',
    description: 'Inspired by the vibrant culture and landscapes of the Malabar coast, this piece captures exotic beauty through rich colors and intricate cultural references.',
    descriptionEs: 'Inspirada en la vibrante cultura y paisajes de la costa de Malabar, esta pieza captura belleza exótica a través de colores ricos y referencias culturales intrincadas.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/malabar.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Malabar',
    translatedDescription: 'Inspired by the vibrant...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-09-01'),
    updatedAt: new Date('2022-09-01')
  },
  {
    id: 'mapu',
    title: 'MAPU',
    titleEs: 'MAPU',
    description: 'A profound connection to ancestral lands and indigenous wisdom, honoring the Mapuche concept of "earth" through contemporary artistic interpretation and cultural respect.',
    descriptionEs: 'Una conexión profunda con tierras ancestrales y sabiduría indígena, honrando el concepto Mapuche de "tierra" a través de interpretación artística contemporánea y respeto cultural.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/MAPU .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'MAPU',
    translatedDescription: 'A profound connection...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-10-01'),
    updatedAt: new Date('2022-10-01')
  },
  {
    id: 'miami-canvas',
    title: 'Miami',
    titleEs: 'Miami',
    description: 'Capturing the electric energy, vibrant culture, and tropical essence of Miami through bold colors, dynamic composition, and urban sophistication.',
    descriptionEs: 'Capturando la energía eléctrica, cultura vibrante y esencia tropical de Miami a través de colores audaces, composición dinámica y sofisticación urbana.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Miami.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Miami',
    translatedDescription: 'Capturing the electric...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15')
  },
  {
    id: 'moneda-2',
    title: 'Moneda II',
    titleEs: 'Moneda II',
    description: 'Part of a series exploring value, exchange, and economic systems through artistic lens, questioning material worth versus spiritual richness.',
    descriptionEs: 'Parte de una serie explorando valor, intercambio y sistemas económicos a través de lente artístico, cuestionando valor material versus riqueza espiritual.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/MONEDA 2-1.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Moneda II',
    translatedDescription: 'Part of a series...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-11-01'),
    updatedAt: new Date('2022-11-01')
  },
  {
    id: 'moneda-1',
    title: 'Moneda I',
    titleEs: 'Moneda I',
    description: 'The first in a contemplative series examining currency, value, and human relationship with material wealth through symbolic artistic representation.',
    descriptionEs: 'La primera en una serie contemplativa examinando moneda, valor y relación humana con riqueza material a través de representación artística simbólica.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/MONEDA1.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Moneda I',
    translatedDescription: 'The first in a...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-11-15'),
    updatedAt: new Date('2022-11-15')
  },
  {
    id: 'mudra',
    title: 'Mudra',
    titleEs: 'Mudra',
    description: 'Sacred hand gestures from yogic tradition brought to life on canvas, each position holding spiritual meaning and energetic significance in contemplative composition.',
    descriptionEs: 'Gestos sagrados de manos de tradición yóguica cobran vida en lienzo, cada posición sosteniendo significado espiritual y significancia energética en composición contemplativa.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/mudra.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Mudra',
    translatedDescription: 'Sacred hand gestures...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-04-15'),
    updatedAt: new Date('2023-04-15')
  },
  {
    id: 'mundo',
    title: 'Mundo',
    titleEs: 'Mundo',
    description: 'A worldly perspective captured in paint, celebrating global diversity, interconnectedness, and our shared home planet through universal artistic language.',
    descriptionEs: 'Una perspectiva mundial capturada en pintura, celebrando diversidad global, interconexión y nuestro hogar planetario compartido a través de lenguaje artístico universal.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/mundo.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Mundo',
    translatedDescription: 'A worldly perspective...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-12-01'),
    updatedAt: new Date('2022-12-01')
  },
  {
    id: 'orange-buddha',
    title: 'Orange Buddha',
    titleEs: 'Buda Naranja',
    description: 'Radiant enlightenment emanates from this vibrant orange Buddha, where warm citrus tones symbolize joy, creativity, and spiritual warmth in meditative serenity.',
    descriptionEs: 'Iluminación radiante emana de este vibrante Buda naranja, donde tonos cálidos cítricos simbolizan alegría, creatividad y calidez espiritual en serenidad meditativa.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Orange Buddha.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Orange Buddha',
    translatedDescription: 'Radiant enlightenment emanates...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2023-05-15')
  },
  {
    id: 'under-the-tree',
    title: 'Under the Tree',
    titleEs: 'Bajo el Árbol',
    description: 'A peaceful sanctuary beneath ancient branches, where figure and nature merge in harmonious meditation, evoking Buddha\'s enlightenment under the Bodhi tree.',
    descriptionEs: 'Un santuario pacífico bajo ramas ancestrales, donde figura y naturaleza se fusionan en meditación armoniosa, evocando la iluminación de Buda bajo el árbol Bodhi.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Under the Tree .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Under the Tree',
    translatedDescription: 'A peaceful sanctuary...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-01-15'),
    updatedAt: new Date('2022-01-15')
  },
  {
    id: 'untitled-artwork',
    title: 'Untitled Composition',
    titleEs: 'Composición Sin Título',
    description: 'An exploratory abstract work that speaks through pure form and color, inviting viewers to find their own meaning in spontaneous artistic expression.',
    descriptionEs: 'Una obra abstracta exploratoria que habla a través de forma y color puros, invitando a espectadores a encontrar su propio significado en expresión artística espontánea.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Digital art on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Untitled-Artwork.png',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Untitled Composition',
    translatedDescription: 'An exploratory abstract...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15')
  },
  {
    id: 'vientre-1995',
    title: 'Vientre 1995',
    titleEs: 'Vientre 1995',
    description: 'An early oil painting exploring themes of femininity, creation, and the womb as source of life, rendered with classical technique and emotional depth.',
    descriptionEs: 'Una pintura temprana al óleo explorando temas de feminidad, creación y el vientre como fuente de vida, representada con técnica clásica y profundidad emocional.',
    location: '',
    year: 1995,
    width: 0,
    height: 0,
    medium: 'Oil on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Vientre1995 oil by fio.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Vientre 1995',
    translatedDescription: 'An early oil painting...',
    dimensions: 'Canvas',
    createdAt: new Date('1995-01-01'),
    updatedAt: new Date('1995-01-01')
  },
  {
    id: 'visita-del-pez',
    title: 'Visita del Pez MAPU',
    titleEs: 'Visita del Pez MAPU',
    description: 'A mystical visitation where the fish becomes messenger and symbol, bridging aquatic realms with earthly wisdom in dreamlike narrative composition.',
    descriptionEs: 'Una visita mística donde el pez se convierte en mensajero y símbolo, uniendo reinos acuáticos con sabiduría terrenal en composición narrativa onírica.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/VISITA DEL PEZ MAPU .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Visita del Pez MAPU',
    translatedDescription: 'A mystical visitation...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-02-15'),
    updatedAt: new Date('2022-02-15')
  },
  {
    id: 'water-free-mind',
    title: 'Water - Free Mind Series',
    titleEs: 'Agua - Serie Mente Libre',
    description: 'Completing the elemental Free Mind series, water flows through this piece representing emotional fluidity, adaptability, and the cleansing power of consciousness.',
    descriptionEs: 'Completando la serie elemental Mente Libre, el agua fluye a través de esta pieza representando fluidez emocional, adaptabilidad y el poder purificador de la conciencia.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Digital art on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Water Free Mind Series.png',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: true,
    translatedTitle: 'Water - Free Mind Series',
    translatedDescription: 'Completing the elemental...',
    dimensions: 'Canvas',
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2023-07-15')
  },
  {
    id: 'canvas-img-1074',
    title: 'Artistic Expression',
    titleEs: 'Expresión Artística',
    description: 'A vibrant canvas work showcasing bold colors and dynamic composition, capturing the essence of contemporary artistic expression through masterful brushwork.',
    descriptionEs: 'Una obra de lienzo vibrante mostrando colores audaces y composición dinámica, capturando la esencia de expresión artística contemporánea a través de pinceladas magistrales.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/IMG_1074.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Artistic Expression',
    translatedDescription: 'A vibrant canvas work...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01')
  },
  {
    id: 'canvas-img-1079',
    title: 'Color Journey',
    titleEs: 'Viaje de Color',
    description: 'An expressive painting exploring color relationships and emotional depth, where each hue contributes to a harmonious and captivating visual narrative.',
    descriptionEs: 'Una pintura expresiva explorando relaciones de color y profundidad emocional, donde cada tonalidad contribuye a una narrativa visual armoniosa y cautivadora.',
    location: '',
    year: 2022,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/IMG_1079.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Color Journey',
    translatedDescription: 'An expressive painting...',
    dimensions: 'Canvas',
    createdAt: new Date('2022-02-01'),
    updatedAt: new Date('2022-02-01')
  },
  {
    id: 'canvas-img-series',
    title: 'Contemporary Visions Series',
    titleEs: 'Serie Visiones Contemporáneas',
    description: 'A collection of contemporary canvas paintings demonstrating versatility in style and technique, each piece a unique exploration of color, form, and artistic expression.',
    descriptionEs: 'Una colección de pinturas contemporáneas en lienzo demostrando versatilidad en estilo y técnica, cada pieza una exploración única de color, forma y expresión artística.',
    location: '',
    year: 2021,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/IMG_1081.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Contemporary Visions Series',
    translatedDescription: 'A collection of contemporary...',
    dimensions: 'Canvas',
    createdAt: new Date('2021-01-01'),
    updatedAt: new Date('2021-01-01')
  },
  {
    id: 'picture-006',
    title: 'Visual Narrative',
    titleEs: 'Narrativa Visual',
    description: 'A compelling canvas painting that tells a story through color and form, inviting viewers to discover layers of meaning in every brushstroke and composition element.',
    descriptionEs: 'Una pintura en lienzo convincente que cuenta una historia a través de color y forma, invitando a espectadores a descubrir capas de significado en cada pincelada y elemento compositivo.',
    location: '',
    year: 2020,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Picture 006.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Visual Narrative',
    translatedDescription: 'A compelling canvas painting...',
    dimensions: 'Canvas',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2020-01-01')
  },
  {
    id: 'picture-009',
    title: 'Abstract Horizons',
    titleEs: 'Horizontes Abstractos',
    description: 'An exploration of abstract landscapes and horizons, where imagination meets technique in a vibrant celebration of color, texture, and boundless creative possibility.',
    descriptionEs: 'Una exploración de paisajes abstractos y horizontes, donde imaginación se encuentra con técnica en una celebración vibrante de color, textura y posibilidad creativa sin límites.',
    location: '',
    year: 2020,
    width: 0,
    height: 0,
    medium: 'Mixed media on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Picture 009.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Abstract Horizons',
    translatedDescription: 'An exploration of abstract...',
    dimensions: 'Canvas',
    createdAt: new Date('2020-06-01'),
    updatedAt: new Date('2020-06-01')
  },
  {
    id: 'picture-024',
    title: 'Chromatic Symphony',
    titleEs: 'Sinfonía Cromática',
    description: 'A harmonious composition where colors sing together in perfect balance, creating a visual symphony that resonates with emotional depth and artistic sophistication.',
    descriptionEs: 'Una composición armoniosa donde colores cantan juntos en perfecto equilibrio, creando una sinfonía visual que resuena con profundidad emocional y sofisticación artística.',
    location: '',
    year: 2021,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Canvas',
    imageUrl: '/images/Portfolio/canvas-works/Picture 024.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Chromatic Symphony',
    translatedDescription: 'A harmonious composition...',
    dimensions: 'Canvas',
    createdAt: new Date('2021-04-01'),
    updatedAt: new Date('2021-04-01')
  },
  // Additional Canvas Works - UUID and IMG series
  { id: '01614e2a-3c31-4e0f-a8ac-b645719b91b6', title: 'Canvas Expression 1', titleEs: 'Expresión en Lienzo 1', description: 'A captivating canvas work showcasing bold brushstrokes and vibrant color harmonies, expressing raw emotion through contemporary painting techniques.', descriptionEs: 'Una obra cautivadora mostrando pinceladas audaces y armonías de colores vibrantes, expresando emoción cruda a través de técnicas de pintura contemporánea.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/01614E2A-3C31-4E0F-A8AC-B645719B91B6.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 1', translatedDescription: 'A captivating canvas work...', dimensions: 'Canvas', createdAt: new Date('2022-01-01'), updatedAt: new Date('2022-01-01') },
  { id: '08498ffd-e1a6-4875-8d81-0dbd321be2d0', title: 'Canvas Expression 2', titleEs: 'Expresión en Lienzo 2', description: 'An expressive piece exploring color relationships and form, where spontaneous gestures meet deliberate composition.', descriptionEs: 'Una pieza expresiva explorando relaciones de color y forma, donde gestos espontáneos encuentran composición deliberada.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/08498FFD-E1A6-4875-8D81-0DBD321BE2D0.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 2', translatedDescription: 'An expressive piece...', dimensions: 'Canvas', createdAt: new Date('2022-01-15'), updatedAt: new Date('2022-01-15') },
  { id: '0c0b4427-5978-4039-847e-a843040883fb', title: 'Canvas Expression 3', titleEs: 'Expresión en Lienzo 3', description: 'A dynamic canvas painting capturing movement and energy through layered colors and textures.', descriptionEs: 'Una pintura dinámica capturando movimiento y energía a través de colores y texturas en capas.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/0C0B4427-5978-4039-847E-A843040883FB.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 3', translatedDescription: 'A dynamic canvas...', dimensions: 'Canvas', createdAt: new Date('2021-03-01'), updatedAt: new Date('2021-03-01') },
  { id: '1ebbea68-0401-457e-b95a-cb1c47e14100', title: 'Canvas Expression 4', titleEs: 'Expresión en Lienzo 4', description: 'Contemporary artwork demonstrating mastery of color theory and composition.', descriptionEs: 'Obra contemporánea demostrando maestría de teoría del color y composición.', location: '', year: 2023, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/1EBBEA68-0401-457E-B95A-CB1C47E14100.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 4', translatedDescription: 'Contemporary artwork...', dimensions: 'Canvas', createdAt: new Date('2023-02-01'), updatedAt: new Date('2023-02-01') },
  { id: '20170531-144059', title: 'Canvas Work 2017-1', titleEs: 'Obra en Lienzo 2017-1', description: 'An artistic exploration combining traditional techniques with modern aesthetics.', descriptionEs: 'Una exploración artística combinando técnicas tradicionales con estética moderna.', location: '', year: 2017, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20170531_144059.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2017-1', translatedDescription: 'An artistic exploration...', dimensions: 'Canvas', createdAt: new Date('2017-05-31'), updatedAt: new Date('2017-05-31') },
  { id: '20190411-125340', title: 'Canvas Work 2019-1', titleEs: 'Obra en Lienzo 2019-1', description: 'A vibrant creation featuring bold color choices and expressive mark-making.', descriptionEs: 'Una creación vibrante con elecciones de color audaces y marcas expresivas.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20190411_125340.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2019-1', translatedDescription: 'A vibrant creation...', dimensions: 'Canvas', createdAt: new Date('2019-04-11'), updatedAt: new Date('2019-04-11') },
  { id: '20190411-125843', title: 'Canvas Work 2019-2', titleEs: 'Obra en Lienzo 2019-2', description: 'Mixed media artwork layering colors, textures, and forms to create depth.', descriptionEs: 'Obra de medios mixtos en capas de colores, texturas y formas para crear profundidad.', location: '', year: 2019, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20190411_125843.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2019-2', translatedDescription: 'Mixed media artwork...', dimensions: 'Canvas', createdAt: new Date('2019-04-11'), updatedAt: new Date('2019-04-11') },
  { id: '20190416-101247', title: 'Canvas Work 2019-3', titleEs: 'Obra en Lienzo 2019-3', description: 'A meditative painting inviting quiet reflection through subtle color shifts.', descriptionEs: 'Una pintura meditativa invitando a reflexión tranquila a través de cambios sutiles de color.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20190416_101247.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2019-3', translatedDescription: 'A meditative painting...', dimensions: 'Canvas', createdAt: new Date('2019-04-16'), updatedAt: new Date('2019-04-16') },
  { id: '20190416-101332', title: 'Canvas Work 2019-4', titleEs: 'Obra en Lienzo 2019-4', description: 'Expressive work celebrating the joy of color and spontaneous creation.', descriptionEs: 'Obra expresiva celebrando la alegría del color y creación espontánea.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20190416_101332.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2019-4', translatedDescription: 'Expressive work...', dimensions: 'Canvas', createdAt: new Date('2019-04-16'), updatedAt: new Date('2019-04-16') },
  { id: '20200507-142838', title: 'Canvas Work 2020-1', titleEs: 'Obra en Lienzo 2020-1', description: 'Contemporary painting exploring abstract forms and vibrant palettes.', descriptionEs: 'Pintura contemporánea explorando formas abstractas y paletas vibrantes.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20200507_142838.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2020-1', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2020-05-07'), updatedAt: new Date('2020-05-07') },
  { id: '20200831-140036', title: 'Canvas Work 2020-2', titleEs: 'Obra en Lienzo 2020-2', description: 'Bold artistic statement combining emotional depth with technical excellence.', descriptionEs: 'Declaración artística audaz combinando profundidad emocional con excelencia técnica.', location: '', year: 2020, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/20200831_140036.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Work 2020-2', translatedDescription: 'Bold artistic statement...', dimensions: 'Canvas', createdAt: new Date('2020-08-31'), updatedAt: new Date('2020-08-31') },
  { id: 'img-0315', title: 'Studio Series 315', titleEs: 'Serie de Estudio 315', description: 'Vibrant studio painting showcasing experimental color techniques and bold composition.', descriptionEs: 'Pintura de estudio vibrante mostrando técnicas de color experimentales y composición audaz.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0315.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 315', translatedDescription: 'Vibrant studio painting...', dimensions: 'Canvas', createdAt: new Date('2022-03-01'), updatedAt: new Date('2022-03-01') },
  { id: 'img-0317', title: 'Studio Series 317', titleEs: 'Serie de Estudio 317', description: 'Expressive artwork exploring the boundaries between abstraction and representation.', descriptionEs: 'Obra expresiva explorando los límites entre abstracción y representación.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0317.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 317', translatedDescription: 'Expressive artwork...', dimensions: 'Canvas', createdAt: new Date('2022-03-15'), updatedAt: new Date('2022-03-15') },
  { id: 'img-0337', title: 'Studio Series 337', titleEs: 'Serie de Estudio 337', description: 'Dynamic canvas work capturing energy through movement and color interaction.', descriptionEs: 'Obra dinámica capturando energía a través de movimiento e interacción de colores.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0337.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 337', translatedDescription: 'Dynamic canvas work...', dimensions: 'Canvas', createdAt: new Date('2022-04-01'), updatedAt: new Date('2022-04-01') },
  { id: 'img-0566', title: 'Studio Series 566', titleEs: 'Serie de Estudio 566', description: 'Contemporary painting demonstrating sophisticated color relationships and balance.', descriptionEs: 'Pintura contemporánea demostrando relaciones de color sofisticadas y equilibrio.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0566.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 566', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2021-06-01'), updatedAt: new Date('2021-06-01') },
  { id: 'img-0567', title: 'Studio Series 567', titleEs: 'Serie de Estudio 567', description: 'Artistic exploration combining intuitive mark-making with thoughtful composition.', descriptionEs: 'Exploración artística combinando marcas intuitivas con composición reflexiva.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0567.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 567', translatedDescription: 'Artistic exploration...', dimensions: 'Canvas', createdAt: new Date('2021-06-15'), updatedAt: new Date('2021-06-15') },
  { id: 'img-0636', title: 'Studio Series 636', titleEs: 'Serie de Estudio 636', description: 'Bold canvas painting featuring rich textures and compelling visual narratives.', descriptionEs: 'Pintura audaz con texturas ricas y narrativas visuales convincentes.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_0636.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 636', translatedDescription: 'Bold canvas painting...', dimensions: 'Canvas', createdAt: new Date('2021-07-01'), updatedAt: new Date('2021-07-01') },
  { id: 'img-1086', title: 'Studio Series 1086', titleEs: 'Serie de Estudio 1086', description: 'Vibrant work celebrating color as the primary means of emotional expression.', descriptionEs: 'Obra vibrante celebrando el color como medio principal de expresión emocional.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1086.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1086', translatedDescription: 'Vibrant work celebrating...', dimensions: 'Canvas', createdAt: new Date('2020-10-01'), updatedAt: new Date('2020-10-01') },
  { id: 'img-1088', title: 'Studio Series 1088', titleEs: 'Serie de Estudio 1088', description: 'Expressive painting where spontaneity and control create perfect harmony.', descriptionEs: 'Pintura expresiva donde espontaneidad y control crean armonía perfecta.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1088.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1088', translatedDescription: 'Expressive painting...', dimensions: 'Canvas', createdAt: new Date('2020-10-15'), updatedAt: new Date('2020-10-15') },
  { id: 'img-1089', title: 'Studio Series 1089', titleEs: 'Serie de Estudio 1089', description: 'Contemporary work exploring the intersection of color, form, and emotion.', descriptionEs: 'Obra contemporánea explorando la intersección de color, forma y emoción.', location: '', year: 2020, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1089.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1089', translatedDescription: 'Contemporary work...', dimensions: 'Canvas', createdAt: new Date('2020-11-01'), updatedAt: new Date('2020-11-01') },
  { id: 'img-1091', title: 'Studio Series 1091', titleEs: 'Serie de Estudio 1091', description: 'Dynamic painting showcasing the artist\'s signature use of layered colors.', descriptionEs: 'Pintura dinámica mostrando el uso característico de colores en capas del artista.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1091.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1091', translatedDescription: 'Dynamic painting...', dimensions: 'Canvas', createdAt: new Date('2020-11-15'), updatedAt: new Date('2020-11-15') },
  { id: 'img-1092', title: 'Studio Series 1092', titleEs: 'Serie de Estudio 1092', description: 'Artistic statement combining technical mastery with emotional authenticity.', descriptionEs: 'Declaración artística combinando maestría técnica con autenticidad emocional.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1092.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1092', translatedDescription: 'Artistic statement...', dimensions: 'Canvas', createdAt: new Date('2020-12-01'), updatedAt: new Date('2020-12-01') },
  { id: 'img-1093', title: 'Studio Series 1093', titleEs: 'Serie de Estudio 1093', description: 'Vibrant canvas exploring bold color contrasts and dynamic composition.', descriptionEs: 'Lienzo vibrante explorando contrastes de color audaces y composición dinámica.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1093.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1093', translatedDescription: 'Vibrant canvas...', dimensions: 'Canvas', createdAt: new Date('2020-12-15'), updatedAt: new Date('2020-12-15') },
  { id: 'img-1094', title: 'Studio Series 1094', titleEs: 'Serie de Estudio 1094', description: 'Expressive work celebrating the freedom of artistic expression.', descriptionEs: 'Obra expresiva celebrando la libertad de expresión artística.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1094.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1094', translatedDescription: 'Expressive work...', dimensions: 'Canvas', createdAt: new Date('2021-01-01'), updatedAt: new Date('2021-01-01') },
  { id: 'img-1097', title: 'Studio Series 1097', titleEs: 'Serie de Estudio 1097', description: 'Contemporary painting demonstrating sophisticated understanding of color theory.', descriptionEs: 'Pintura contemporánea demostrando comprensión sofisticada de teoría del color.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1097.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1097', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2021-01-15'), updatedAt: new Date('2021-01-15') },
  { id: 'img-1100', title: 'Studio Series 1100', titleEs: 'Serie de Estudio 1100', description: 'Artistic exploration where texture and color create visual depth.', descriptionEs: 'Exploración artística donde textura y color crean profundidad visual.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1100.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1100', translatedDescription: 'Artistic exploration...', dimensions: 'Canvas', createdAt: new Date('2021-02-01'), updatedAt: new Date('2021-02-01') },
  { id: 'img-1103', title: 'Studio Series 1103', titleEs: 'Serie de Estudio 1103', description: 'Bold work combining spontaneous gestures with deliberate composition.', descriptionEs: 'Obra audaz combinando gestos espontáneos con composición deliberada.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1103.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1103', translatedDescription: 'Bold work combining...', dimensions: 'Canvas', createdAt: new Date('2021-02-15'), updatedAt: new Date('2021-02-15') },
  { id: 'img-1105', title: 'Studio Series 1105', titleEs: 'Serie de Estudio 1105', description: 'Vibrant painting celebrating the joy of pure color and form.', descriptionEs: 'Pintura vibrante celebrando la alegría del color y forma puros.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1105.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1105', translatedDescription: 'Vibrant painting...', dimensions: 'Canvas', createdAt: new Date('2021-03-01'), updatedAt: new Date('2021-03-01') },
  { id: 'img-1106', title: 'Studio Series 1106', titleEs: 'Serie de Estudio 1106', description: 'Expressive canvas work demonstrating mastery of layering techniques.', descriptionEs: 'Obra expresiva demostrando maestría de técnicas de capas.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1106.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1106', translatedDescription: 'Expressive canvas work...', dimensions: 'Canvas', createdAt: new Date('2021-03-15'), updatedAt: new Date('2021-03-15') },
  { id: 'img-1112', title: 'Studio Series 1112', titleEs: 'Serie de Estudio 1112', description: 'Contemporary work exploring dynamic color relationships and visual rhythm.', descriptionEs: 'Obra contemporánea explorando relaciones de color dinámicas y ritmo visual.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1112.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1112', translatedDescription: 'Contemporary work...', dimensions: 'Canvas', createdAt: new Date('2021-04-01'), updatedAt: new Date('2021-04-01') },
  { id: 'img-1113', title: 'Studio Series 1113', titleEs: 'Serie de Estudio 1113', description: 'Artistic statement combining emotional expression with technical excellence.', descriptionEs: 'Declaración artística combinando expresión emocional con excelencia técnica.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1113.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1113', translatedDescription: 'Artistic statement...', dimensions: 'Canvas', createdAt: new Date('2021-04-15'), updatedAt: new Date('2021-04-15') },
  { id: 'img-1127', title: 'Studio Series 1127', titleEs: 'Serie de Estudio 1127', description: 'Bold painting showcasing confident brushwork and vibrant color palette.', descriptionEs: 'Pintura audaz mostrando pinceladas confiadas y paleta de colores vibrante.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1127.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1127', translatedDescription: 'Bold painting...', dimensions: 'Canvas', createdAt: new Date('2021-05-01'), updatedAt: new Date('2021-05-01') },
  { id: 'img-1129', title: 'Studio Series 1129', titleEs: 'Serie de Estudio 1129', description: 'Vibrant work celebrating spontaneity and artistic freedom.', descriptionEs: 'Obra vibrante celebrando espontaneidad y libertad artística.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1129.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1129', translatedDescription: 'Vibrant work...', dimensions: 'Canvas', createdAt: new Date('2021-05-15'), updatedAt: new Date('2021-05-15') },
  { id: 'img-1907', title: 'Studio Series 1907', titleEs: 'Serie de Estudio 1907', description: 'Expressive canvas exploring the interplay of light, color, and texture.', descriptionEs: 'Lienzo expresivo explorando la interacción de luz, color y textura.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1907.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1907', translatedDescription: 'Expressive canvas...', dimensions: 'Canvas', createdAt: new Date('2019-07-01'), updatedAt: new Date('2019-07-01') },
  { id: 'img-1953', title: 'Studio Series 1953', titleEs: 'Serie de Estudio 1953', description: 'Contemporary painting demonstrating sophisticated color harmonies.', descriptionEs: 'Pintura contemporánea demostrando armonías de color sofisticadas.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_1953.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 1953', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2019-08-01'), updatedAt: new Date('2019-08-01') },
  { id: 'img-5822-1', title: 'Studio Series 5822', titleEs: 'Serie de Estudio 5822', description: 'Contemporary masterpiece celebrating color, form, and artistic expression.', descriptionEs: 'Obra maestra contemporánea celebrando color, forma y expresión artística.', location: '', year: 2016, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/IMG_5822-1.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Studio Series 5822', translatedDescription: 'Contemporary masterpiece...', dimensions: 'Canvas', createdAt: new Date('2016-07-01'), updatedAt: new Date('2016-07-01') },
  { id: '29-7a-00', title: 'Canvas Series 29-7A', titleEs: 'Serie de Lienzo 29-7A', description: 'Contemporary painting showcasing sophisticated artistic vision and technique.', descriptionEs: 'Pintura contemporánea mostrando visión artística sofisticada y técnica.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/29_7A_00.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Series 29-7A', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2019-01-01'), updatedAt: new Date('2019-01-01') },
  { id: '36-21a', title: 'Canvas Series 36-21A', titleEs: 'Serie de Lienzo 36-21A', description: 'Expressive work combining bold color choices with dynamic composition.', descriptionEs: 'Obra expresiva combinando elecciones de color audaces con composición dinámica.', location: '', year: 2019, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/36_21A.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Series 36-21A', translatedDescription: 'Expressive work...', dimensions: 'Canvas', createdAt: new Date('2019-02-01'), updatedAt: new Date('2019-02-01') },
  { id: '37-22a', title: 'Canvas Series 37-22A', titleEs: 'Serie de Lienzo 37-22A', description: 'Artistic exploration celebrating the joy of color and creative expression.', descriptionEs: 'Exploración artística celebrando la alegría del color y expresión creativa.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/37_22A.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Series 37-22A', translatedDescription: 'Artistic exploration...', dimensions: 'Canvas', createdAt: new Date('2019-03-01'), updatedAt: new Date('2019-03-01') },
  { id: '38-13a', title: 'Canvas Series 38-13A', titleEs: 'Serie de Lienzo 38-13A', description: 'Bold painting demonstrating mastery of layering and texture techniques.', descriptionEs: 'Pintura audaz demostrando maestría de técnicas de capas y textura.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/38_13A.JPG', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Series 38-13A', translatedDescription: 'Bold painting...', dimensions: 'Canvas', createdAt: new Date('2019-04-01'), updatedAt: new Date('2019-04-01') },
  { id: '218b35be-d416-4c0e-bca0-ad1189c2f68f', title: 'Canvas Expression 5', titleEs: 'Expresión en Lienzo 5', description: 'Vibrant contemporary work celebrating color and artistic freedom.', descriptionEs: 'Obra contemporánea vibrante celebrando color y libertad artística.', location: '', year: 2022, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/218B35BE-D416-4C0E-BCA0-AD1189C2F68F.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 5', translatedDescription: 'Vibrant contemporary work...', dimensions: 'Canvas', createdAt: new Date('2022-02-01'), updatedAt: new Date('2022-02-01') },
  { id: '2ca35b10-c5e2-40fe-921d-6134c2385c34', title: 'Canvas Expression 6', titleEs: 'Expresión en Lienzo 6', description: 'Expressive painting combining emotional depth with vibrant colors.', descriptionEs: 'Pintura expresiva combinando profundidad emocional con colores vibrantes.', location: '', year: 2022, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/2CA35B10-C5E2-40FE-921D-6134C2385C34.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 6', translatedDescription: 'Expressive painting...', dimensions: 'Canvas', createdAt: new Date('2022-03-01'), updatedAt: new Date('2022-03-01') },
  { id: '4fc64f00-103c-42f5-8cd7-2c399a58638e', title: 'Canvas Expression 7', titleEs: 'Expresión en Lienzo 7', description: 'Contemporary masterpiece showcasing sophisticated color relationships.', descriptionEs: 'Obra maestra contemporánea mostrando relaciones de color sofisticadas.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/4FC64F00-103C-42F5-8CD7-2C399A58638E.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 7', translatedDescription: 'Contemporary masterpiece...', dimensions: 'Canvas', createdAt: new Date('2021-07-01'), updatedAt: new Date('2021-07-01') },
  { id: '7543c5e6-0548-4570-aea1-f273035de3cc', title: 'Canvas Expression 8', titleEs: 'Expresión en Lienzo 8', description: 'Bold artistic statement celebrating expressive freedom and creativity.', descriptionEs: 'Declaración artística audaz celebrando libertad expresiva y creatividad.', location: '', year: 2021, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/7543C5E6-0548-4570-AEA1-F273035DE3CC.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 8', translatedDescription: 'Bold artistic statement...', dimensions: 'Canvas', createdAt: new Date('2021-08-01'), updatedAt: new Date('2021-08-01') },
  { id: '7dd48984-d87a-4a3f-a4f7-c7bbe185d36e', title: 'Canvas Expression 9', titleEs: 'Expresión en Lienzo 9', description: 'Vibrant work exploring dynamic movement through color and form.', descriptionEs: 'Obra vibrante explorando movimiento dinámico a través de color y forma.', location: '', year: 2021, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/7DD48984-D87A-4A3F-A4F7-C7BBE185D36E.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 9', translatedDescription: 'Vibrant work...', dimensions: 'Canvas', createdAt: new Date('2021-09-01'), updatedAt: new Date('2021-09-01') },
  { id: '7f0e7a55-ef86-4dfa-8787-7d51714d2de2', title: 'Canvas Expression 10', titleEs: 'Expresión en Lienzo 10', description: 'Contemporary painting demonstrating mastery of color and composition.', descriptionEs: 'Pintura contemporánea demostrando maestría de color y composición.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/7F0E7A55-EF86-4DFA-8787-7D51714D2DE2.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 10', translatedDescription: 'Contemporary painting...', dimensions: 'Canvas', createdAt: new Date('2020-07-01'), updatedAt: new Date('2020-07-01') },
  { id: '7f10237a-eb3e-4812-a1f0-9d1245135a6a', title: 'Canvas Expression 11', titleEs: 'Expresión en Lienzo 11', description: 'Expressive canvas work celebrating artistic vision and technique.', descriptionEs: 'Obra expresiva celebrando visión artística y técnica.', location: '', year: 2020, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/7F10237A-EB3E-4812-A1F0-9D1245135A6A.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 11', translatedDescription: 'Expressive canvas work...', dimensions: 'Canvas', createdAt: new Date('2020-08-01'), updatedAt: new Date('2020-08-01') },
  { id: '804f1859-e71a-4e8c-9a79-904f2cb1cdd9', title: 'Canvas Expression 12', titleEs: 'Expresión en Lienzo 12', description: 'Artistic exploration combining bold colors with dynamic energy.', descriptionEs: 'Exploración artística combinando colores audaces con energía dinámica.', location: '', year: 2020, width: 0, height: 0, medium: 'Mixed media on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/804F1859-E71A-4E8C-9A79-904F2CB1CDD9.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 12', translatedDescription: 'Artistic exploration...', dimensions: 'Canvas', createdAt: new Date('2020-09-01'), updatedAt: new Date('2020-09-01') },
  { id: '8370d12e-1f3b-4889-8d75-e493f851c4d2', title: 'Canvas Expression 13', titleEs: 'Expresión en Lienzo 13', description: 'Bold painting showcasing vibrant color palette and creative vision.', descriptionEs: 'Pintura audaz mostrando paleta de colores vibrante y visión creativa.', location: '', year: 2019, width: 0, height: 0, medium: 'Acrylic on canvas', client: '', category: 'Canvas', imageUrl: '/images/Portfolio/canvas-works/8370D12E-1F3B-4889-8D75-E493F851C4D2.jpg', beforeImageUrl: null, afterImageUrl: null, featured: false, translatedTitle: 'Canvas Expression 13', translatedDescription: 'Bold painting...', dimensions: 'Canvas', createdAt: new Date('2019-12-01'), updatedAt: new Date('2019-12-01') },
  
  // DETAIL SHOTS - Close-ups highlighting artistic technique
  {
    id: 'detail-akasha-frog',
    title: 'Akasha Frog - Detail',
    titleEs: 'Rana Akasha - Detalle',
    description: 'An intimate view revealing the intricate brushwork, layered textures, and fine details that bring spiritual depth to the Akasha Frog composition.',
    descriptionEs: 'Una vista íntima revelando pinceladas intrincadas, texturas en capas y detalles finos que aportan profundidad espiritual a la composición Rana Akasha.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Acrylic on canvas',
    client: '',
    category: 'Details',
    imageUrl: '/images/Portfolio/details/Detail Akasha Frog .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Akasha Frog - Detail',
    translatedDescription: 'An intimate view...',
    dimensions: 'Detail Shot',
    createdAt: new Date('2023-05-01'),
    updatedAt: new Date('2023-05-01')
  },
  {
    id: 'seahorse-detail-color',
    title: 'Seahorse - Color Detail',
    titleEs: 'Caballito de Mar - Detalle Color',
    description: 'A macro perspective showcasing the vibrant color palette and delicate brushstrokes used to capture the ethereal beauty of the seahorse form.',
    descriptionEs: 'Una perspectiva macro mostrando la paleta de colores vibrantes y pinceladas delicadas usadas para capturar la belleza etérea de la forma del caballito de mar.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Detail photography',
    client: '',
    category: 'Details',
    imageUrl: '/images/Portfolio/details/Seahorse detail color.JPG',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Seahorse - Color Detail',
    translatedDescription: 'A macro perspective...',
    dimensions: 'Detail Shot',
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2023-08-15')
  },
  {
    id: 'seahorse-talk-detail',
    title: 'Seahorse Talk - Detail',
    titleEs: 'Conversación de Caballito de Mar - Detalle',
    description: 'Close examination of the narrative elements and artistic technique in Seahorse Talk, revealing hidden details and masterful execution.',
    descriptionEs: 'Examen cercano de elementos narrativos y técnica artística en Conversación de Caballito de Mar, revelando detalles ocultos y ejecución magistral.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Detail photography',
    client: '',
    category: 'Details',
    imageUrl: '/images/Portfolio/details/SEAHORSE TALK detail.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Seahorse Talk - Detail',
    translatedDescription: 'Close examination...',
    dimensions: 'Detail Shot',
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2023-08-20')
  },

  {
    id: 'tangerine-buddha-detail-2',
    title: 'Tangerine Buddha - Detail II',
    titleEs: 'Buda Tangerina - Detalle II',
    description: 'A second detailed view revealing additional layers of complexity, color transitions, and the artist\'s meticulous approach to sacred subject matter.',
    descriptionEs: 'Una segunda vista detallada revelando capas adicionales de complejidad, transiciones de color y el enfoque meticuloso del artista hacia materia sagrada.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Detail photography',
    client: '',
    category: 'Details',
    imageUrl: '/images/Portfolio/details/Tangerine Buddha detail 2 .jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Tangerine Buddha - Detail II',
    translatedDescription: 'A second detailed view...',
    dimensions: 'Detail Shot',
    createdAt: new Date('2023-05-21'),
    updatedAt: new Date('2023-05-21')
  },

  // INSTALLATIONS - Special projects and collaborative works
  {
    id: 'fiorella-podesta',
    title: 'Artist Portrait',
    titleEs: 'Retrato de la Artista',
    description: 'An intimate portrait of Fiorella Podestá in her creative element, capturing the passion and dedication behind 30+ years of artistic excellence.',
    descriptionEs: 'Un retrato íntimo de Fiorella Podestá en su elemento creativo, capturando la pasión y dedicación detrás de más de 30 años de excelencia artística.',
    location: '',
    year: 2023,
    width: 0,
    height: 0,
    medium: 'Photography',
    client: '',
    category: 'About',
    imageUrl: '/images/Portfolio/installations/fiorellapodesta.jpg',
    beforeImageUrl: null,
    afterImageUrl: null,
    featured: false,
    translatedTitle: 'Artist Portrait',
    translatedDescription: 'An intimate portrait...',
    dimensions: 'Portrait',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-09-01')
  }
];
