(function(){
  'use strict';
  var A={ctx:null,master:null,music:null,sfx:null,filter:null,started:false,nextBeat:0,step:0,drone:[],settings:null,intensity:0};
  function init(settings){A.settings=settings;if(A.started){resume();return}var C=window.AudioContext||window.webkitAudioContext;if(!C)return;A.ctx=new C();A.master=A.ctx.createGain();A.music=A.ctx.createGain();A.sfx=A.ctx.createGain();A.filter=A.ctx.createBiquadFilter();A.filter.type='lowpass';A.filter.frequency.value=1200;A.filter.Q.value=1.2;A.music.connect(A.filter).connect(A.master);A.sfx.connect(A.master);A.master.connect(A.ctx.destination);A.master.gain.value=.72;A.music.gain.value=settings.music?.18:0;A.sfx.gain.value=settings.sfx?.7:0;startDrone();A.nextBeat=A.ctx.currentTime+.08;A.started=true}
  function resume(){if(A.ctx&&A.ctx.state==='suspended')A.ctx.resume()}
  function startDrone(){var freqs=[55,82.41,110];freqs.forEach(function(f,i){var o=A.ctx.createOscillator(),g=A.ctx.createGain(),pan=A.ctx.createStereoPanner?A.ctx.createStereoPanner():null;o.type=i===0?'sine':'triangle';o.frequency.value=f;g.gain.value=i===0?.035:.014;if(pan){pan.pan.value=i===1?-.45:i===2?.45:0;o.connect(g).connect(pan).connect(A.music)}else{o.connect(g).connect(A.music)}o.start();A.drone.push({o:o,g:g})});var lfo=A.ctx.createOscillator(),lg=A.ctx.createGain();lfo.frequency.value=.07;lg.gain.value=430;lfo.connect(lg).connect(A.filter.frequency);lfo.start()}
  function setSettings(settings){A.settings=settings;if(!A.started)return;A.music.gain.setTargetAtTime(settings.music?.18:0,A.ctx.currentTime,.08);A.sfx.gain.setTargetAtTime(settings.sfx?.7:0,A.ctx.currentTime,.08)}
  function osc(freq,dur,type,vol,slide,pan){if(!A.started||!A.settings.sfx)return;var now=A.ctx.currentTime,o=A.ctx.createOscillator(),g=A.ctx.createGain(),p=A.ctx.createStereoPanner?A.ctx.createStereoPanner():null;o.type=type||'sine';o.frequency.setValueAtTime(Math.max(20,freq),now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(vol||.05,now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+dur);if(p){p.pan.value=pan||0;o.connect(g).connect(p).connect(A.sfx)}else{o.connect(g).connect(A.sfx)}o.start(now);o.stop(now+dur+.025)}
  function noise(dur,vol,cutoff){if(!A.started||!A.settings.sfx)return;var len=Math.max(1,Math.floor(A.ctx.sampleRate*dur)),buf=A.ctx.createBuffer(1,len,A.ctx.sampleRate),d=buf.getChannelData(0);for(var i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);var src=A.ctx.createBufferSource(),f=A.ctx.createBiquadFilter(),g=A.ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=cutoff||900;g.gain.setValueAtTime(vol||.05,A.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,A.ctx.currentTime+dur);src.connect(f).connect(g).connect(A.sfx);src.start();src.stop(A.ctx.currentTime+dur)}
  function chord(root,quality,dur,vol){if(!A.started||!A.settings.sfx)return;var ratios=quality==='minor'?[1,1.1892,1.4983]:[1,1.2599,1.4983];ratios.forEach(function(r,i){setTimeout(function(){osc(root*r,dur,'sine',(vol||.035)/(i+1),root*r*.08)},i*28)})}
  function tick(intensity,boss,combo){if(!A.started||!A.settings.music)return;resume();A.intensity=intensity||0;var now=A.ctx.currentTime;if(now<A.nextBeat)return;var rate=boss?.25:Math.max(.34,.62-A.intensity*.18);A.nextBeat=now+rate;var scale=[0,3,7,10,12,15,19,22],root=boss?55:65.41,idx=(A.step+(combo>5?2:0))%scale.length,f=root*Math.pow(2,scale[idx]/12);var o=A.ctx.createOscillator(),g=A.ctx.createGain(),p=A.ctx.createStereoPanner?A.ctx.createStereoPanner():null;o.type=boss?'sawtooth':'triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(boss?.035:.022+A.intensity*.012,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+rate*.82);if(p){p.pan.value=Math.sin(A.step*.9)*.55;o.connect(g).connect(p).connect(A.music)}else{o.connect(g).connect(A.music)}o.start(now);o.stop(now+rate);if(A.step%4===0){var bass=A.ctx.createOscillator(),bg=A.ctx.createGain();bass.type='sine';bass.frequency.value=boss?41.2:32.7;bg.gain.setValueAtTime(.025+A.intensity*.018,now);bg.gain.exponentialRampToValueAtTime(.0001,now+.24);bass.connect(bg).connect(A.music);bass.start(now);bass.stop(now+.25)}A.filter.frequency.setTargetAtTime(800+A.intensity*1700+(boss?500:0),now,.08);A.step++}
  A.init=init;A.resume=resume;A.setSettings=setSettings;A.tick=tick;
  A.ui=function(){osc(420,.06,'sine',.028,90)};
  A.collect=function(value,combo){osc(value>1?780:580+Math.min(combo,10)*18,.075,'sine',.045,180);if(value>1)osc(1040,.09,'triangle',.028,140,.25)};
  A.near=function(combo){osc(240+combo*22,.045,'triangle',.03,80,(combo%2?-.4:.4))};
  A.hit=function(){noise(.19,.13,650);osc(170,.24,'sawtooth',.075,-105)};
  A.shield=function(){osc(520,.18,'sine',.055,350);osc(780,.12,'triangle',.025,-180)};
  A.shieldBreak=function(){noise(.15,.09,1400);osc(310,.18,'square',.045,-180)};
  A.nova=function(){noise(.48,.14,1800);osc(130,.55,'sawtooth',.08,850);setTimeout(function(){chord(261.63,'major',.45,.04)},80)};
  A.level=function(){chord(329.63,'major',.4,.045);setTimeout(function(){osc(987.77,.18,'sine',.035,240)},120)};
  A.wave=function(){chord(220,'minor',.34,.042);setTimeout(function(){chord(329.63,'major',.38,.04)},150)};
  A.bossEnter=function(){noise(.6,.1,450);osc(55,.75,'sawtooth',.07,28)};
  A.bossHit=function(){osc(125,.045,'square',.025,-18)};
  A.bossDown=function(){noise(.8,.15,1100);osc(82,.8,'sawtooth',.09,780);setTimeout(function(){chord(220,'major',.7,.055)},220)};
  A.achievement=function(){chord(392,'major',.5,.055);setTimeout(function(){osc(1174,.25,'sine',.04,220)},130)};
  A.gameOver=function(){chord(110,'minor',.8,.05);osc(180,.65,'sawtooth',.04,-120)};
  window.SpaceAudio=A;
})();
