'use strict';
addDaily=function(type,amount){var d=ensureDaily();if(META.daily.claimed||d.type!==type)return;META.daily.progress=Math.min(d.goal,META.daily.progress+(amount||1));if(META.daily.progress>=d.goal){META.daily.claimed=true;META.credits+=d.reward;queueReward('DAILY CONTRACT COMPLETE',d.reward);SpaceAudio.achievement();haptic([18,30,45])}saveMeta();if(STATE.mode!=='playing')refreshMetaUI()};
function bindButton(id,fn){var node=byId(id),locked=false;node.addEventListener('pointerup',function(e){e.preventDefault();if(locked)return;locked=true;SpaceAudio.init(META.settings);SpaceAudio.resume();fn();setTimeout(function(){locked=false},220)});node.addEventListener('click',function(e){e.preventDefault()})}
function openMenu(){STATE.mode='menu';showGameUi(false);showScreen(UI.menu);refreshMetaUI();SpaceAudio.ui()}
function openHangar(){showScreen(UI.hangar);renderSkins();SpaceAudio.ui()}
function openAchievements(){showScreen(UI.achievements);renderAchievements();SpaceAudio.ui()}
function openSettings(){showScreen(UI.settings);refreshSettings();SpaceAudio.ui()}
function toggleSetting(key){META.settings[key]=!META.settings[key];saveMeta();refreshSettings();SpaceAudio.ui()}
canvas.addEventListener('pointerdown',function(e){if(STATE.mode!=='playing')return;STATE.drag=true;PLAYER.targetX=pointerX(e);canvas.setPointerCapture&&canvas.setPointerCapture(e.pointerId);e.preventDefault()},{passive:false});
canvas.addEventListener('pointermove',function(e){if(STATE.mode!=='playing'||!STATE.drag)return;PLAYER.targetX=pointerX(e);e.preventDefault()},{passive:false});
canvas.addEventListener('pointerup',function(e){STATE.drag=false;canvas.releasePointerCapture&&canvas.releasePointerCapture(e.pointerId);e.preventDefault()},{passive:false});
canvas.addEventListener('pointercancel',function(){STATE.drag=false});
window.addEventListener('keydown',function(e){if(STATE.mode==='playing'){if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')PLAYER.targetX=Math.max(18,PLAYER.targetX-55);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')PLAYER.targetX=Math.min(STATE.w-18,PLAYER.targetX+55);if(e.key===' '||e.key.toLowerCase()==='n')activateNova();if(e.key==='Escape')pauseRun()}else if(STATE.mode==='paused'&&e.key==='Escape')resumeRun()});
bindButton('start',startRun);bindButton('again',startRun);bindButton('pause',pauseRun);bindButton('resume',resumeRun);bindButton('restartPause',startRun);bindButton('quit',quitRun);bindButton('nova',activateNova);bindButton('hangar',openHangar);bindButton('hangarBack',openMenu);bindButton('achievements',openAchievements);bindButton('achievementsBack',openMenu);bindButton('settings',openSettings);bindButton('settingsBack',openMenu);bindButton('gameOverHangar',openHangar);bindButton('gameOverMenu',openMenu);bindButton('musicToggle',function(){toggleSetting('music')});bindButton('sfxToggle',function(){toggleSetting('sfx')});bindButton('hapticsToggle',function(){toggleSetting('haptics')});bindButton('flashToggle',function(){toggleSetting('reducedFlash')});
document.addEventListener('visibilitychange',function(){if(document.hidden&&STATE.mode==='playing')pauseRun()});window.addEventListener('resize',resizeGame,{passive:true});window.addEventListener('orientationchange',function(){setTimeout(resizeGame,120)},{passive:true});
resizeGame();ensureDaily();checkAchievements();refreshMetaUI();showScreen(UI.menu);STATE.last=performance.now();requestAnimationFrame(animationLoop);
if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0)window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js?v=4').catch(function(){})});
