'use strict';
var TAU=Math.PI*2;
var canvas=document.getElementById('game');
var ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
function byId(id){return document.getElementById(id)}
var UI={
  screens:[byId('menuScreen'),byId('hangarScreen'),byId('achievementsScreen'),byId('settingsScreen'),byId('pauseScreen'),byId('upgradeScreen'),byId('rewardScreen'),byId('gameOverScreen')],
  menu:byId('menuScreen'),hangar:byId('hangarScreen'),achievements:byId('achievementsScreen'),settings:byId('settingsScreen'),pauseScreen:byId('pauseScreen'),upgrade:byId('upgradeScreen'),reward:byId('rewardScreen'),gameOver:byId('gameOverScreen'),
  hud:byId('hud'),score:byId('score'),energy:byId('energy'),wave:byId('wave'),lives:byId('lives'),comboHud:byId('comboHud'),multiplier:byId('multiplier'),runLevel:byId('runLevel'),runLevelText:byId('runLevelText'),runXpFill:byId('runXpFill'),bossBar:byId('bossBar'),bossFill:byId('bossFill'),bossName:byId('bossName'),bossPhase:byId('bossPhase'),pause:byId('pause'),nova:byId('nova'),novaFill:byId('novaFill'),novaText:byId('novaText'),contractHud:byId('contractHud'),contractText:byId('contractText'),contractFill:byId('contractFill'),toast:byId('toast'),waveBanner:byId('waveBanner'),waveBannerTop:byId('waveBannerTop'),waveBannerMain:byId('waveBannerMain'),waveBannerSub:byId('waveBannerSub'),tutorial:byId('tutorialHint'),
  metaLevel:byId('metaLevel'),metaXpText:byId('metaXpText'),metaXpPercent:byId('metaXpPercent'),metaXpFill:byId('metaXpFill'),bestScore:byId('bestScore'),highestWave:byId('highestWave'),metaBosses:byId('metaBosses'),credits:byId('credits'),dailyText:byId('dailyText'),dailyFill:byId('dailyFill'),dailyProgress:byId('dailyProgress'),dailyReward:byId('dailyReward'),hangarCredits:byId('hangarCredits'),skinGrid:byId('skinGrid'),achievementList:byId('achievementList'),musicToggle:byId('musicToggle'),sfxToggle:byId('sfxToggle'),hapticsToggle:byId('hapticsToggle'),flashToggle:byId('flashToggle'),upgradeEyebrow:byId('upgradeEyebrow'),upgradeTitle:byId('upgradeTitle'),upgradeSubtitle:byId('upgradeSubtitle'),upgradeList:byId('upgradeList'),rewardList:byId('rewardList'),resultEyebrow:byId('resultEyebrow'),finalScore:byId('finalScore'),finalWave:byId('finalWave'),finalBosses:byId('finalBosses'),finalCombo:byId('finalCombo'),finalCredits:byId('finalCredits'),xpGain:byId('xpGain'),endXpFill:byId('endXpFill'),endLevelText:byId('endLevelText'),runSummary:byId('runSummary')
};
var DEFAULT_SAVE={version:4,bestScore:0,highestWave:1,credits:0,totalCores:0,bosses:0,runs:0,xp:0,novas:0,maxCombo:0,ownedSkins:['cyan'],skin:'cyan',achievements:{},daily:{date:'',type:'',progress:0,claimed:false},settings:{music:true,sfx:true,haptics:true,reducedFlash:false},tutorialSeen:false};
function loadSave(){var raw=null;try{raw=JSON.parse(localStorage.getItem('neonOrbitComplete')||'null')}catch(e){}if(!raw){var oldCredits=+localStorage.getItem('novaCredits')||0,oldBest=+localStorage.getItem('novaBest')||0,oldSkin=localStorage.getItem('novaSkin')||'cyan',oldOwned=null;try{oldOwned=JSON.parse(localStorage.getItem('novaOwned')||'null')}catch(e){}raw={credits:oldCredits,bestScore:oldBest,skin:oldSkin,ownedSkins:Array.isArray(oldOwned)?oldOwned:['cyan']}}var data=Object.assign({},DEFAULT_SAVE,raw||{});data.settings=Object.assign({},DEFAULT_SAVE.settings,(raw&&raw.settings)||{});data.achievements=Object.assign({},(raw&&raw.achievements)||{});data.ownedSkins=Array.isArray(data.ownedSkins)?data.ownedSkins:['cyan'];if(data.ownedSkins.indexOf('cyan')<0)data.ownedSkins.unshift('cyan');return data}
var META=loadSave();
function saveMeta(){localStorage.setItem('neonOrbitComplete',JSON.stringify(META))}
function metaLevelInfo(xp){var level=1,need=150,left=xp;while(left>=need){left-=need;level++;need=Math.floor(150*Math.pow(1.17,level-1))}return{level:level,current:left,need:need,pct:left/need}}
var SKINS={cyan:{name:'AQUA',color:'#42f5ff',accent:'#7fffff',cost:0},pink:{name:'NOVA',color:'#ff4fd8',accent:'#ff9aec',cost:140},gold:{name:'SOLAR',color:'#ffe66d',accent:'#fff4a8',cost:300},violet:{name:'RIFT',color:'#9b7bff',accent:'#c7b8ff',cost:520},green:{name:'ION',color:'#79ff91',accent:'#baffc5',cost:780},white:{name:'GHOST',color:'#ffffff',accent:'#bfe8ff',cost:1050},red:{name:'EMBER',color:'#ff5e68',accent:'#ffb0a8',cost:1400},prism:{name:'PRISM',color:'#75fff1',accent:'#ff65da',cost:1900}};
var ACHIEVEMENTS={firstRun:{icon:'🚀',name:'FIRST ASCENSION',desc:'Complete your first run.',reward:25,test:function(){return META.runs>=1}},cores100:{icon:'✦',name:'STAR HARVESTER',desc:'Collect 100 energy cores.',reward:75,test:function(){return META.totalCores>=100}},bosses3:{icon:'⬢',name:'SENTINEL BREAKER',desc:'Destroy 3 bosses.',reward:110,test:function(){return META.bosses>=3}},wave10:{icon:'∞',name:'DEEP ORBIT',desc:'Reach wave 10.',reward:150,test:function(){return META.highestWave>=10}},score10k:{icon:'◆',name:'FIVE DIGITS',desc:'Score 10,000 points in one run.',reward:140,test:function(){return META.bestScore>=10000}},combo12:{icon:'⚡',name:'PERFECT FLOW',desc:'Reach a 12-chain near-miss combo.',reward:100,test:function(){return META.maxCombo>=12}},nova25:{icon:'☄',name:'SUPERNOVA',desc:'Activate Nova Pulse 25 times.',reward:120,test:function(){return META.novas>=25}},commander10:{icon:'★',name:'VETERAN PILOT',desc:'Reach Commander Level 10.',reward:220,test:function(){return metaLevelInfo(META.xp).level>=10}}};
var DAILY_TYPES=[{type:'cores',text:'Collect 35 energy cores',goal:35,reward:75},{type:'near',text:'Score 22 near-misses',goal:22,reward:75},{type:'boss',text:'Destroy a Void Sentinel',goal:1,reward:90},{type:'score',text:'Earn 7,500 total score',goal:7500,reward:80},{type:'waves',text:'Clear 7 total waves',goal:7,reward:85}];
function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function hashDate(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function ensureDaily(){var key=dateKey();if(META.daily.date!==key){var d=DAILY_TYPES[hashDate(key)%DAILY_TYPES.length];META.daily={date:key,type:d.type,progress:0,claimed:false};saveMeta()}return DAILY_TYPES.filter(function(x){return x.type===META.daily.type})[0]||DAILY_TYPES[0]}
function addDaily(type,amount){var d=ensureDaily();if(META.daily.claimed||d.type!==type)return;META.daily.progress=Math.min(d.goal,META.daily.progress+(amount||1));if(META.daily.progress>=d.goal){META.daily.claimed=true;META.credits+=d.reward;queueReward('DAILY CONTRACT COMPLETE',d.reward);SpaceAudio.achievement();haptic([18,30,45])}saveMeta();refreshMetaUI()}
function checkAchievements(){Object.keys(ACHIEVEMENTS).forEach(function(key){var a=ACHIEVEMENTS[key];if(!META.achievements[key]&&a.test()){META.achievements[key]=true;META.credits+=a.reward;queueReward('ACHIEVEMENT: '+a.name,a.reward);SpaceAudio.achievement();haptic([18,25,18,25,50])}});saveMeta()}
var STATE={mode:'menu',w:0,h:0,dpr:1,last:0,time:0,score:0,wave:1,waveClock:0,waveDuration:24,lives:3,energy:100,maxEnergy:100,runXp:0,runLevel:1,nextRunXp:70,cores:0,runCredits:0,bosses:0,combo:0,maxCombo:0,comboTimer:0,multiplier:1,nova:0,novaMax:100,novaUses:0,shield:0,slow:0,magnet:0,overdrive:0,invuln:0,hitStop:0,timeScale:1,shake:0,flash:0,chromatic:0,spawnTimer:.4,coreTimer:.7,powerTimer:7,playerShotTimer:0,boss:null,bossPending:false,bossRewardPending:false,transition:false,levelPending:false,contract:null,contractProgress:0,contractDone:false,tutorialStep:0,upgrades:{},stats:{near:0,waves:0,damageTaken:0},mods:{score:1,regen:0,hitbox:1,magnet:0,novaRate:1,coreValue:1,fireRate:1,damage:1,comboGrace:0,luck:0,shieldStart:0,lifeBonus:0,energyDrain:1,critical:0,revive:false}};
var PLAYER={x:0,y:0,targetX:0,r:14,trail:[],tilt:0};
var obstacles=[],cores=[],powers=[],particles=[],floating=[],shockwaves=[],playerBullets=[],enemyBullets=[],warnings=[],backgroundStars=[],nebulae=[];
var rewardQueue=[],toastTimer=0,waveTimer=0,tutorialTimer=0;
function haptic(pattern){if(META.settings.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function showScreen(screen){UI.screens.forEach(function(s){s.classList.add('hidden')});if(screen)screen.classList.remove('hidden')}
function showGameUi(show){[UI.hud,UI.runLevel,UI.contractHud].forEach(function(n){n.classList.toggle('show',show)});UI.pause.classList.toggle('show',show);UI.nova.classList.toggle('show',show);if(!show)UI.bossBar.classList.remove('show')}
function toast(text,duration){UI.toast.textContent=text;UI.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){UI.toast.classList.remove('show');showNextReward()},duration||900)}
function queueReward(label,amount){rewardQueue.push({label:label,amount:amount});if(!UI.toast.classList.contains('show'))showNextReward()}
function showNextReward(){if(!rewardQueue.length)return;var r=rewardQueue.shift();toast(r.label+'  +'+r.amount+' CREDITS',1450)}
function waveBanner(top,main,sub){UI.waveBannerTop.textContent=top;UI.waveBannerMain.textContent=main;UI.waveBannerSub.textContent=sub||'';UI.waveBanner.classList.add('show');clearTimeout(waveTimer);waveTimer=setTimeout(function(){UI.waveBanner.classList.remove('show')},1450)}
function showTutorial(text,duration){if(META.tutorialSeen)return;UI.tutorial.textContent=text;UI.tutorial.classList.remove('hidden');clearTimeout(tutorialTimer);tutorialTimer=setTimeout(function(){UI.tutorial.classList.add('hidden')},duration||2500)}
function resizeGame(){STATE.dpr=Math.min(window.devicePixelRatio||1,2);STATE.w=window.innerWidth;STATE.h=window.innerHeight;canvas.width=Math.round(STATE.w*STATE.dpr);canvas.height=Math.round(STATE.h*STATE.dpr);canvas.style.width=STATE.w+'px';canvas.style.height=STATE.h+'px';ctx.setTransform(STATE.dpr,0,0,STATE.dpr,0,0);PLAYER.y=STATE.h*.79;if(!PLAYER.x)PLAYER.x=PLAYER.targetX=STATE.w/2;createBackground()}
function createBackground(){backgroundStars=[];nebulae=[];var count=Math.min(145,Math.floor(STATE.w*STATE.h/5200));for(var i=0;i<count;i++)backgroundStars.push({x:Math.random()*STATE.w,y:Math.random()*STATE.h,z:.15+Math.random()*.85,a:.12+Math.random()*.55,tw:Math.random()*TAU});for(i=0;i<5;i++)nebulae.push({x:Math.random()*STATE.w,y:Math.random()*STATE.h,r:120+Math.random()*210,h:Math.random()*360,a:.025+Math.random()*.035})}
function randomContract(){var pool=[{type:'cores',text:'Collect 10 cores',goal:10},{type:'near',text:'Score 7 near-misses',goal:7},{type:'survive',text:'Survive 20 seconds',goal:20},{type:'nova',text:'Activate Nova Pulse',goal:1},{type:'wave',text:'Clear the current wave',goal:1}];return Object.assign({progress:0},pool[Math.floor(Math.random()*pool.length)])}
function resetRun(){obstacles=[];cores=[];powers=[];particles=[];floating=[];shockwaves=[];playerBullets=[];enemyBullets=[];warnings=[];PLAYER.trail=[];PLAYER.x=PLAYER.targetX=STATE.w/2;PLAYER.y=STATE.h*.79;Object.assign(STATE,{time:0,score:0,wave:1,waveClock:0,lives:3,energy:100,maxEnergy:100,runXp:0,runLevel:1,nextRunXp:70,cores:0,runCredits:0,bosses:0,combo:0,maxCombo:0,comboTimer:0,multiplier:1,nova:0,novaUses:0,shield:0,slow:0,magnet:0,overdrive:0,invuln:0,hitStop:0,timeScale:1,shake:0,flash:0,chromatic:0,spawnTimer:.45,coreTimer:.65,powerTimer:6.5,playerShotTimer:0,boss:null,bossPending:false,bossRewardPending:false,transition:false,levelPending:false,contract:randomContract(),contractProgress:0,contractDone:false,tutorialStep:0,upgrades:{},stats:{near:0,waves:0,damageTaken:0},mods:{score:1,regen:0,hitbox:1,magnet:0,novaRate:1,coreValue:1,fireRate:1,damage:1,comboGrace:0,luck:0,shieldStart:0,lifeBonus:0,energyDrain:1,critical:0,revive:false}});syncRunUI();updateContractUI()}
function startRun(){SpaceAudio.init(META.settings);SpaceAudio.resume();SpaceAudio.ui();resetRun();STATE.mode='playing';showScreen(null);showGameUi(true);STATE.last=performance.now();waveBanner('SECTOR 01','WAVE 1','BUILD YOUR FLOW');if(!META.tutorialSeen){setTimeout(function(){showTutorial('DRAG ANYWHERE TO STEER THE PULSE',2800)},500);setTimeout(function(){showTutorial('NEAR-MISS HAZARDS TO BUILD FLOW AND CHARGE NOVA',3300)},3500);setTimeout(function(){showTutorial('TAP NOVA WHEN THE BUTTON REACHES 100%',2800);META.tutorialSeen=true;saveMeta()},7200)}}
function pauseRun(){if(STATE.mode!=='playing')return;STATE.mode='paused';showScreen(UI.pauseScreen);UI.pause.classList.remove('show');UI.nova.classList.remove('show')}
function resumeRun(){if(STATE.mode!=='paused')return;STATE.mode='playing';showScreen(null);UI.pause.classList.add('show');UI.nova.classList.add('show');STATE.last=performance.now();SpaceAudio.resume();SpaceAudio.ui()}
function quitRun(){if(STATE.mode==='menu')return;endRun(false)}
function runXpGain(amount){STATE.runXp+=amount;while(STATE.runXp>=STATE.nextRunXp){STATE.runXp-=STATE.nextRunXp;STATE.runLevel++;STATE.nextRunXp=Math.floor(70*Math.pow(1.16,STATE.runLevel-1));STATE.levelPending=true}if(STATE.levelPending&&STATE.mode==='playing'&&!STATE.bossRewardPending)openUpgrade(false)}
function addScore(amount,label,x,y){var earned=Math.floor(amount*STATE.multiplier*STATE.mods.score);STATE.score+=earned;if(label)floatingText(x||PLAYER.x,y||PLAYER.y-25,label+' +'+earned,'#ffe66d',1);return earned}
function addRunCredits(amount,x,y){STATE.runCredits+=amount;floatingText(x||PLAYER.x,y||PLAYER.y-32,'+'+amount+' CREDIT'+(amount===1?'':'S'),'#ffe66d',.9)}
function updateContract(type,amount){if(STATE.contractDone||!STATE.contract||STATE.contract.type!==type)return;STATE.contractProgress=Math.min(STATE.contract.goal,STATE.contractProgress+(amount||1));if(STATE.contractProgress>=STATE.contract.goal){STATE.contractDone=true;addScore(350,'CONTRACT',PLAYER.x,PLAYER.y-55);addRunCredits(15,PLAYER.x,PLAYER.y-78);toast('RUN CONTRACT COMPLETE');SpaceAudio.achievement();haptic([15,25,40])}updateContractUI()}
function updateContractUI(){if(!STATE.contract)return;UI.contractText.textContent=STATE.contract.text+'  '+Math.floor(STATE.contractProgress)+'/'+STATE.contract.goal;UI.contractFill.style.transform='scaleX('+Math.min(1,STATE.contractProgress/STATE.contract.goal)+')'}
function openUpgrade(bossRelic){if(STATE.mode!=='playing')return;STATE.mode=bossRelic?'reward':'upgrade';STATE.levelPending=false;UI.pause.classList.remove('show');UI.nova.classList.remove('show');UI.upgradeEyebrow.textContent=bossRelic?'COSMIC RELIC':'PULSE LEVEL '+STATE.runLevel;UI.upgradeTitle.textContent=bossRelic?'Choose a Boss Relic':'Choose an Upgrade';UI.upgradeSubtitle.textContent=bossRelic?'One empowered relic. Permanent for this run.':'Shape your build. Every choice changes the run.';buildUpgradeCards(bossRelic?UI.rewardList:UI.upgradeList,bossRelic);showScreen(bossRelic?UI.reward:UI.upgrade);SpaceAudio.level();haptic([12,22,34])}
var UPGRADE_DEFS={reactor:{icon:'◆',name:'EXPANDED REACTOR',desc:'+25 maximum energy and restore 25.',max:5,apply:function(power){STATE.maxEnergy+=25*power;STATE.energy=Math.min(STATE.maxEnergy,STATE.energy+25*power)}},repair:{icon:'↻',name:'NANO REPAIR',desc:'Regenerate energy every second.',max:5,apply:function(power){STATE.mods.regen+=.85*power}},phase:{icon:'◉',name:'PHASE SHELL',desc:'Shrink your collision profile.',max:4,apply:function(power){STATE.mods.hitbox*=Math.pow(.88,power)}},gravity:{icon:'⌁',name:'GRAVITY WELL',desc:'Permanently attract nearby cores.',max:4,apply:function(power){STATE.mods.magnet+=55*power}},reactorScore:{icon:'✦',name:'SCORE REACTOR',desc:'+30% score from every source.',max:5,apply:function(power){STATE.mods.score+=.3*power}},novaEngine:{icon:'⚡',name:'NOVA ENGINE',desc:'Charge Nova substantially faster.',max:5,apply:function(power){STATE.mods.novaRate+=.28*power}},coreYield:{icon:'◇',name:'CORE AMPLIFIER',desc:'Cores restore more energy and XP.',max:4,apply:function(power){STATE.mods.coreValue+=.3*power}},combo:{icon:'∞',name:'FLOW STABILIZER',desc:'Combos decay more slowly.',max:4,apply:function(power){STATE.mods.comboGrace+=.7*power}},life:{icon:'♥',name:'ECHO LIFE',desc:'Gain one life immediately.',max:3,apply:function(power){STATE.lives+=power;STATE.mods.lifeBonus+=power}},shield:{icon:'⬡',name:'AEGIS ARRAY',desc:'Gain a shield now and at each wave.',max:3,apply:function(power){STATE.shield=Math.max(STATE.shield,7+power*2);STATE.mods.shieldStart+=power}},weapon:{icon:'➤',name:'BOSS BREAKER',desc:'Increase auto-cannon damage.',max:5,apply:function(power){STATE.mods.damage+=.35*power}},rapid:{icon:'≋',name:'RAPID ARRAY',desc:'Increase auto-cannon fire rate.',max:4,apply:function(power){STATE.mods.fireRate+=.25*power}},luck:{icon:'☄',name:'COSMIC LUCK',desc:'More golden cores and power-ups.',max:4,apply:function(power){STATE.mods.luck+=.2*power}},critical:{icon:'★',name:'CRITICAL MASS',desc:'Auto-cannon shots can critically hit.',max:4,apply:function(power){STATE.mods.critical+=.12*power}},overdrive:{icon:'☀',name:'PERMANENT OVERDRIVE',desc:'Flow multiplier builds faster.',max:3,apply:function(power){STATE.multiplier+=.35*power}},revive:{icon:'✚',name:'QUANTUM RETURN',desc:'Survive one fatal impact.',max:1,apply:function(){STATE.mods.revive=true}}};
function availableUpgrades(bossRelic){var keys=Object.keys(UPGRADE_DEFS).filter(function(k){return (STATE.upgrades[k]||0)<UPGRADE_DEFS[k].max});var choices=[];var count=3;while(choices.length<count&&keys.length){var index=Math.floor(Math.random()*keys.length);choices.push(keys.splice(index,1)[0])}return choices.map(function(key){var roll=Math.random()+STATE.mods.luck*.08+(bossRelic?.45:0),rarity=roll>.92?'legendary':roll>.58?'rare':'common',power=rarity==='legendary'?2:rarity==='rare'?1.45:1;if(bossRelic){rarity=roll>.95?'legendary':'rare';power=rarity==='legendary'?2.4:1.75}return{key:key,rarity:rarity,power:power}})}
function buildUpgradeCards(container,bossRelic){container.innerHTML='';availableUpgrades(bossRelic).forEach(function(choice){var def=UPGRADE_DEFS[choice.key],card=document.createElement('button');card.className='upgradeCard '+choice.rarity;card.innerHTML='<div class="upgradeTop"><div class="upgradeIcon">'+def.icon+'</div><div class="upgradeCopy"><strong>'+def.name+'</strong><span>'+def.desc+'</span></div><div class="rarity">'+choice.rarity.toUpperCase()+'</div></div>';card.addEventListener('pointerup',function(e){e.preventDefault();STATE.upgrades[choice.key]=(STATE.upgrades[choice.key]||0)+1;def.apply(choice.power);showScreen(null);STATE.mode='playing';STATE.bossRewardPending=false;STATE.transition=false;UI.pause.classList.add('show');UI.nova.classList.add('show');STATE.last=performance.now();floatingText(PLAYER.x,PLAYER.y-60,def.name,choice.rarity==='legendary'?'#ffe66d':choice.rarity==='rare'?'#c8b8ff':'#42f5ff',1.3);SpaceAudio.level();syncRunUI();if(bossRelic)waveBanner('RIFT CLOSED','WAVE '+STATE.wave,'ASCENSION CONTINUES');if(STATE.levelPending)setTimeout(function(){if(STATE.mode==='playing')openUpgrade(false)},280)});container.appendChild(card)})}
function endRun(natural){if(STATE.mode==='ended')return;STATE.mode='ended';showGameUi(false);UI.tutorial.classList.add('hidden');SpaceAudio.gameOver();haptic([35,35,75]);var final=Math.floor(STATE.score),isBest=final>META.bestScore,xpEarned=Math.floor(final/18+STATE.wave*28+STATE.bosses*110+STATE.cores*2);META.runs++;META.bestScore=Math.max(META.bestScore,final);META.highestWave=Math.max(META.highestWave,STATE.wave);META.totalCores+=STATE.cores;META.bosses+=STATE.bosses;META.novas+=STATE.novaUses;META.maxCombo=Math.max(META.maxCombo,STATE.maxCombo);META.credits+=STATE.runCredits;META.xp+=xpEarned;addDaily('score',final);addDaily('waves',STATE.stats.waves);checkAchievements();saveMeta();var levelInfo=metaLevelInfo(META.xp);UI.resultEyebrow.textContent=isBest?'NEW PERSONAL RECORD':'RUN COMPLETE';UI.resultEyebrow.classList.toggle('newRecord',isBest);UI.finalScore.textContent=final.toLocaleString();UI.finalWave.textContent=STATE.wave;UI.finalBosses.textContent=STATE.bosses;UI.finalCombo.textContent=STATE.maxCombo;UI.finalCredits.textContent='+'+STATE.runCredits;UI.xpGain.textContent='+'+xpEarned+' XP';UI.endXpFill.style.transform='scaleX('+levelInfo.pct+')';UI.endLevelText.textContent='Commander Level '+levelInfo.level+' • '+levelInfo.current+' / '+levelInfo.need+' XP';UI.runSummary.textContent=summaryForRun(isBest,natural);setTimeout(function(){showScreen(UI.gameOver);refreshMetaUI()},420)}
function summaryForRun(isBest,natural){if(isBest)return'Your strongest orbit yet. The next sector is waiting.';if(STATE.bosses>=2)return'Boss breaker. Your build reached deep space.';if(STATE.maxCombo>=10)return'Your Flow was elite. Chase an even longer chain.';if(!natural)return'Run ended. Every attempt still earns progression.';return'Every run strengthens your command profile.'}
function renderSkins(){UI.skinGrid.innerHTML='';UI.hangarCredits.textContent=META.credits.toLocaleString();Object.keys(SKINS).forEach(function(key){var skin=SKINS[key],owned=META.ownedSkins.indexOf(key)>-1,card=document.createElement('button');card.className='skinCard '+(META.skin===key?'selected ':'')+(owned?'':'locked');var orbStyle=key==='prism'?'background:conic-gradient(#42f5ff,#ff4fd8,#ffe66d,#79ff91,#42f5ff);color:#fff':'background:'+skin.color+';color:'+skin.color;card.innerHTML='<div class="skinOrb" style="'+orbStyle+'"></div><strong>'+skin.name+'</strong><small>'+(owned?(META.skin===key?'EQUIPPED':'OWNED'):skin.cost+' CREDITS')+'</small>';card.addEventListener('pointerup',function(e){e.preventDefault();SpaceAudio.ui();if(owned){META.skin=key;saveMeta();renderSkins()}else if(META.credits>=skin.cost){META.credits-=skin.cost;META.ownedSkins.push(key);META.skin=key;saveMeta();renderSkins();refreshMetaUI();toast('NEW CORE UNLOCKED');SpaceAudio.achievement();haptic([15,25,45])}else toast('NEED '+(skin.cost-META.credits)+' MORE CREDITS')});UI.skinGrid.appendChild(card)})}
function renderAchievements(){UI.achievementList.innerHTML='';Object.keys(ACHIEVEMENTS).forEach(function(key){var a=ACHIEVEMENTS[key],done=!!META.achievements[key],card=document.createElement('div');card.className='achievementCard '+(done?'done':'');card.innerHTML='<div class="achievementIcon">'+(done?'✓':a.icon)+'</div><div class="achievementCopy"><strong>'+a.name+'</strong><span>'+a.desc+'</span></div><div class="achievementReward">'+(done?'UNLOCKED':'+'+a.reward)+'</div>';UI.achievementList.appendChild(card)})}
function refreshSettings(){[['musicToggle','music'],['sfxToggle','sfx'],['hapticsToggle','haptics'],['flashToggle','reducedFlash']].forEach(function(pair){UI[pair[0]].classList.toggle('on',!!META.settings[pair[1]])});SpaceAudio.setSettings(META.settings)}
function refreshMetaUI(){var info=metaLevelInfo(META.xp),daily=ensureDaily();UI.metaLevel.textContent=info.level;UI.metaXpText.textContent=info.current.toLocaleString()+' / '+info.need.toLocaleString()+' XP';UI.metaXpPercent.textContent=Math.floor(info.pct*100)+'%';UI.metaXpFill.style.transform='scaleX('+info.pct+')';UI.bestScore.textContent=META.bestScore.toLocaleString();UI.highestWave.textContent=META.highestWave;UI.metaBosses.textContent=META.bosses;UI.credits.textContent=META.credits.toLocaleString();UI.dailyText.textContent=daily.text;UI.dailyFill.style.transform='scaleX('+Math.min(1,META.daily.progress/daily.goal)+')';UI.dailyProgress.textContent=Math.floor(META.daily.progress)+' / '+daily.goal+(META.daily.claimed?' • COMPLETE':'');UI.dailyReward.textContent=META.daily.claimed?'✓':'+'+daily.reward;renderSkins();renderAchievements();refreshSettings()}
function syncRunUI(){UI.score.textContent=Math.floor(STATE.score).toLocaleString();UI.energy.style.transform='scaleX('+Math.max(0,STATE.energy/STATE.maxEnergy)+')';UI.wave.textContent=STATE.wave;UI.lives.textContent='●'.repeat(Math.max(0,STATE.lives));UI.multiplier.textContent='x'+STATE.multiplier.toFixed(1);UI.comboHud.classList.toggle('active',STATE.combo>0);UI.runLevelText.textContent='PULSE LV '+STATE.runLevel;UI.runXpFill.style.transform='scaleX('+Math.min(1,STATE.runXp/STATE.nextRunXp)+')';UI.novaText.textContent=Math.floor(STATE.nova)+'%';UI.novaFill.style.height=Math.min(100,STATE.nova)+'%';UI.nova.classList.toggle('ready',STATE.nova>=STATE.novaMax)}
