var TAU=Math.PI*2;
var canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
var el={menu:q('menu'),hangar:q('hangarScreen'),paused:q('paused'),level:q('levelUp'),over:q('over'),hud:q('hud'),bossBar:q('bossBar'),pause:q('pause'),pulse:q('pulse'),notice:q('notice'),mission:q('mission'),score:q('score'),energy:q('energy'),wave:q('wave'),lives:q('lives'),bossFill:q('bossFill'),pulseValue:q('pulseValue'),missionText:q('missionText'),missionFill:q('missionFill'),bestMenu:q('bestMenu'),creditsMenu:q('creditsMenu'),skinGrid:q('skinGrid'),upgradeList:q('upgradeList'),final:q('final'),finalWave:q('finalWave'),finalCores:q('finalCores'),finalCredits:q('finalCredits'),summary:q('summary'),resultTag:q('resultTag')};
function q(id){return document.getElementById(id)}
var save={best:+localStorage.getItem('novaBest')||0,credits:+localStorage.getItem('novaCredits')||0,skin:localStorage.getItem('novaSkin')||'cyan',owned:JSON.parse(localStorage.getItem('novaOwned')||'["cyan"]')};
var skins={cyan:{name:'Aqua',color:'#42f5ff',cost:0},pink:{name:'Nova',color:'#ff4fd8',cost:120},gold:{name:'Solar',color:'#ffe66d',cost:260},violet:{name:'Rift',color:'#9b7bff',cost:450},lime:{name:'Ion',color:'#79ff91',cost:700},white:{name:'Ghost',color:'#ffffff',cost:1000}};
var S={mode:'menu',w:0,h:0,dpr:1,last:0,time:0,score:0,wave:1,waveTime:0,waveLength:22,lives:3,energy:100,maxEnergy:100,cores:0,runCredits:0,combo:0,comboTime:0,spawn:0,coreSpawn:0,powerSpawn:0,bulletSpawn:0,shield:0,slow:0,magnet:0,invuln:0,nova:0,novaMax:100,shake:0,flash:0,drag:false,boss:null,bossPending:false,transition:false,mission:null,missionDone:false,upgrade:{energy:0,score:0,hitbox:0,regen:0,magnet:0,nova:0,life:0},scoreMult:1,regen:0};
var P={x:0,y:0,target:0,r:14,trail:[]};
var obstacles=[],cores=[],powers=[],particles=[],bullets=[],enemyBullets=[],stars=[];
var audio=null,toastTimer=0;
function resize(){S.dpr=Math.min(devicePixelRatio||1,2);S.w=innerWidth;S.h=innerHeight;canvas.width=Math.round(S.w*S.dpr);canvas.height=Math.round(S.h*S.dpr);ctx.setTransform(S.dpr,0,0,S.dpr,0,0);P.y=S.h*.79;if(!P.x)P.x=P.target=S.w/2;makeStars()}
function makeStars(){stars=[];for(var i=0;i<Math.min(130,Math.floor(S.w*S.h/5700));i++)stars.push({x:Math.random()*S.w,y:Math.random()*S.h,z:.18+Math.random()*.82,a:.12+Math.random()*.55})}
function initAudio(){if(!audio){var A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A()}if(audio&&audio.state==='suspended')audio.resume()}
function tone(freq,dur,type,vol,slide){if(!audio)return;var now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type||'sine';o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(vol||.04,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g).connect(audio.destination);o.start(now);o.stop(now+dur+.02)}
function buzz(p){if(navigator.vibrate)navigator.vibrate(p)}
function bind(id,fn){var node=q(id),locked=false;node.addEventListener('pointerup',function(e){e.preventDefault();if(locked)return;locked=true;fn();setTimeout(function(){locked=false},250)});node.addEventListener('click',function(e){e.preventDefault()})}
function show(screen){[el.menu,el.hangar,el.paused,el.level,el.over].forEach(function(n){n.classList.add('hidden')});if(screen)screen.classList.remove('hidden')}
function toast(text){el.notice.textContent=text;el.notice.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.notice.classList.remove('show')},950)}
function store(){localStorage.setItem('novaBest',save.best);localStorage.setItem('novaCredits',save.credits);localStorage.setItem('novaSkin',save.skin);localStorage.setItem('novaOwned',JSON.stringify(save.owned))}
function refreshMenu(){el.bestMenu.textContent=save.best.toLocaleString();el.creditsMenu.textContent=save.credits.toLocaleString();renderSkins()}
function renderSkins(){el.skinGrid.innerHTML='';Object.keys(skins).forEach(function(key){var sk=skins[key],owned=save.owned.indexOf(key)>-1,btn=document.createElement('button');btn.className='skin'+(save.skin===key?' selected':'')+(owned?'':' locked');btn.innerHTML='<div class="orbPreview" style="background:'+sk.color+';color:'+sk.color+'"></div><div class="skinName">'+sk.name+'</div><div class="skinCost">'+(owned?(save.skin===key?'EQUIPPED':'OWNED'):sk.cost+' CREDITS')+'</div>';btn.addEventListener('pointerup',function(e){e.preventDefault();if(owned){save.skin=key;store();renderSkins();tone(520,.08,'sine',.04,140)}else if(save.credits>=sk.cost){save.credits-=sk.cost;save.owned.push(key);save.skin=key;store();refreshMenu();toast('CORE UNLOCKED');tone(440,.22,'triangle',.06,420)}else{toast('NEED '+(sk.cost-save.credits)+' MORE CREDITS')}});el.skinGrid.appendChild(btn)})}
function randomMission(){var pool=[{type:'cores',goal:8,text:'Collect 8 energy cores'},{type:'near',goal:5,text:'Score 5 near-misses'},{type:'survive',goal:16,text:'Survive 16 seconds'},{type:'nova',goal:1,text:'Activate one Nova Pulse'}];return pool[Math.floor(Math.random()*pool.length)]}
function reset(){obstacles=[];cores=[];powers=[];particles=[];bullets=[];enemyBullets=[];P.trail=[];P.x=P.target=S.w/2;P.y=S.h*.79;Object.assign(S,{time:0,score:0,wave:1,waveTime:0,lives:3,energy:100,maxEnergy:100,cores:0,runCredits:0,combo:0,comboTime:0,spawn:.45,coreSpawn:.75,powerSpawn:7,bulletSpawn:0,shield:0,slow:0,magnet:0,invuln:0,nova:0,shake:0,flash:0,boss:null,bossPending:false,transition:false,mission:randomMission(),missionDone:false,upgrade:{energy:0,score:0,hitbox:0,regen:0,magnet:0,nova:0,life:0},scoreMult:1,regen:0});updateMissionUI();syncHud()}
function start(){initAudio();reset();S.mode='play';show(null);el.hud.classList.add('show');el.pause.classList.add('show');el.pulse.classList.add('show');el.mission.classList.add('show');el.bossBar.classList.remove('show');S.last=performance.now();tone(260,.12,'sine',.06,420)}
function pause(){if(S.mode!=='play')return;S.mode='pause';show(el.paused);el.pause.classList.remove('show');el.pulse.classList.remove('show')}
function resume(){if(S.mode!=='pause')return;S.mode='play';show(null);el.pause.classList.add('show');el.pulse.classList.add('show');S.last=performance.now();tone(330,.08,'sine',.04,80)}
function finish(){if(S.mode==='over')return;S.mode='over';burst(P.x,P.y,skins[save.skin].color,46,1.5);S.shake=18;S.flash=1;tone(170,.35,'sawtooth',.07,-120);buzz([35,35,70]);var final=Math.floor(S.score),newBest=final>save.best;if(newBest)save.best=final;save.credits+=S.runCredits;store();el.final.textContent=final.toLocaleString();el.finalWave.textContent=S.wave;el.finalCores.textContent=S.cores;el.finalCredits.textContent='+'+S.runCredits;el.resultTag.textContent=newBest?'NEW PERSONAL RECORD':'RUN COMPLETE';el.resultTag.className='eyebrow'+(newBest?' newBest':'');el.summary.textContent=S.boss?'The Sentinel ended your ascension.':'The void remembers every run.';setTimeout(function(){show(el.over);el.hud.classList.remove('show');el.pause.classList.remove('show');el.pulse.classList.remove('show');el.mission.classList.remove('show');el.bossBar.classList.remove('show');refreshMenu()},420)}
function loseLife(){if(S.invuln>0)return;S.lives--;S.invuln=1.5;S.shake=13;S.flash=.65;S.energy=Math.max(30,S.energy-20);burst(P.x,P.y,'#ff4fd8',24,1);tone(185,.18,'square',.06,-70);buzz([25,30,25]);if(S.lives<=0)finish();else toast('PULSE FRACTURED — '+S.lives+' LEFT')}
function nextWave(){if(S.transition||S.mode!=='play')return;S.transition=true;S.mode='upgrade';S.wave++;S.waveTime=0;obstacles=[];enemyBullets=[];bullets=[];S.energy=Math.min(S.maxEnergy,S.energy+28);S.mission=randomMission();S.missionDone=false;updateMissionUI();buildUpgradeChoices();setTimeout(function(){show(el.level);el.pause.classList.remove('show');el.pulse.classList.remove('show')},280)}
var upgradeDefs={energy:{icon:'◆',name:'Expanded Core',desc:'+20 maximum energy and refill.',max:4,apply:function(){S.upgrade.energy++;S.maxEnergy+=20;S.energy=S.maxEnergy}},score:{icon:'✦',name:'Score Reactor',desc:'+25% score from all sources.',max:4,apply:function(){S.upgrade.score++;S.scoreMult+=.25}},hitbox:{icon:'◉',name:'Phase Shell',desc:'Smaller collision profile.',max:3,apply:function(){S.upgrade.hitbox++}},regen:{icon:'↻',name:'Self Repair',desc:'Slowly regenerate energy.',max:4,apply:function(){S.upgrade.regen++;S.regen+=.7}},magnet:{icon:'⌁',name:'Gravity Well',desc:'Permanently attract nearby cores.',max:3,apply:function(){S.upgrade.magnet++}},nova:{icon:'⚡',name:'Nova Engine',desc:'Nova charges 20% faster.',max:4,apply:function(){S.upgrade.nova++}},life:{icon:'♥',name:'Echo Life',desc:'Gain one extra life now.',max:2,apply:function(){S.upgrade.life++;S.lives++}}};
function buildUpgradeChoices(){var keys=Object.keys(upgradeDefs).filter(function(k){return S.upgrade[k]<upgradeDefs[k].max}),choices=[];while(choices.length<3&&keys.length){var n=Math.floor(Math.random()*keys.length);choices.push(keys.splice(n,1)[0])}el.upgradeList.innerHTML='';choices.forEach(function(k){var d=upgradeDefs[k],b=document.createElement('button');b.className='upgrade';b.innerHTML='<div class="upgradeTop"><div class="upgradeIcon">'+d.icon+'</div><div><div class="upgradeName">'+d.name+'</div><div class="upgradeDesc">'+d.desc+'</div></div><div class="upgradeLevel">LV '+(S.upgrade[k]+1)+'</div></div>';b.addEventListener('pointerup',function(e){e.preventDefault();d.apply();S.mode='play';S.transition=false;show(null);el.pause.classList.add('show');el.pulse.classList.add('show');if(S.wave%3===0){S.bossPending=true;toast('VOID SENTINEL APPROACHING')}else toast('WAVE '+S.wave);S.last=performance.now();tone(460,.16,'triangle',.06,280)});el.upgradeList.appendChild(b)})}
function missionProgress(){if(!S.mission)return 0;if(S.mission.type==='cores')return Math.min(S.mission.goal,S.cores%S.mission.goal);if(S.mission.type==='near')return Math.min(S.mission.goal,S.combo);if(S.mission.type==='survive')return Math.min(S.mission.goal,S.waveTime);if(S.mission.type==='nova')return S.missionDone?1:0;return 0}
function updateMissionUI(){if(!S.mission)return;var p=missionProgress();el.missionText.textContent=S.mission.text+' ('+Math.floor(p)+'/'+S.mission.goal+')';el.missionFill.style.transform='scaleX('+Math.min(1,p/S.mission.goal)+')';if(!S.missionDone&&p>=S.mission.goal){S.missionDone=true;S.runCredits+=12;S.score+=250*S.scoreMult;toast('MISSION COMPLETE +12');tone(700,.14,'sine',.05,240)}}