'use strict';
function spawnObstacle(){
  var difficulty=Math.min(1.8,STATE.time/75+STATE.wave*.06),roll=Math.random(),type=roll<.38?'shard':roll<.57?'bar':roll<.72?'seeker':roll<.86?'spinner':'mine';
  var size=22+Math.random()*(28+difficulty*8),o={type:type,x:28+Math.random()*(STATE.w-56),y:-60,w:size,h:size,a:Math.random()*TAU,spin:(Math.random()-.5)*(1.1+difficulty),vx:(Math.random()-.5)*(24+difficulty*18),near:false,t:0,exploded:false};
  if(type==='bar'){o.w=Math.min(72+Math.random()*110,STATE.w*.5);o.h=15+Math.random()*12;o.spin=(Math.random()-.5)*.25}
  if(type==='seeker'){o.w=o.h=25+Math.random()*6;o.vx=0}
  if(type==='spinner'){o.w=o.h=40;o.spin=(Math.random()<.5?-1:1)*(2.2+difficulty)}
  if(type==='mine'){o.w=o.h=32;o.vx=0;o.spin=1.5;o.triggerY=STATE.h*(.35+Math.random()*.28)}
  obstacles.push(o)
}
function spawnGate(){var gap=Math.max(86,125-STATE.wave*2),center=gap/2+26+Math.random()*(STATE.w-gap-52),left=center-gap/2,right=center+gap/2;obstacles.push({type:'bar',x:left/2,y:-45,w:left,h:18,a:0,spin:0,vx:0,near:false,t:0});obstacles.push({type:'bar',x:right+(STATE.w-right)/2,y:-45,w:STATE.w-right,h:18,a:0,spin:0,vx:0,near:false,t:0})}
function spawnCore(){var golden=Math.random()<.09+STATE.mods.luck*.08,value=golden?3:1;cores.push({x:28+Math.random()*(STATE.w-56),y:-28,r:golden?10:8,t:Math.random()*TAU,value:value,golden:golden,credit:golden?2:(Math.random()<.32?1:0)})}
function spawnCoreTrail(){var base=45+Math.random()*(STATE.w-90);for(var i=0;i<5;i++)cores.push({x:Math.max(25,Math.min(STATE.w-25,base+Math.sin(i*.9)*38)),y:-25-i*44,r:8,t:i,value:1,golden:false,credit:i===4?1:0})}
function spawnPower(){var types=['shield','slow','magnet','heal','overdrive','nova'],weights=[.22,.16,.17,.19,.14,.12],r=Math.random(),sum=0,type=types[0];for(var i=0;i<types.length;i++){sum+=weights[i];if(r<=sum){type=types[i];break}}powers.push({x:36+Math.random()*(STATE.w-72),y:-32,r:14,t:0,type:type})}
function spawnBoss(){STATE.bossPending=false;STATE.boss={name:STATE.wave<8?'VOID SENTINEL':STATE.wave<16?'RIFT WARDEN':'THE NULL STAR',x:STATE.w/2,y:-110,targetY:128,r:58,hp:220+STATE.wave*48,maxHp:220+STATE.wave*48,t:0,shotTimer:1.1,patternTimer:2.8,phase:1,entering:true};UI.bossName.textContent=STATE.boss.name;UI.bossPhase.textContent='PHASE I';UI.bossFill.style.transform='scaleX(1)';UI.bossBar.classList.add('show');waveBanner('WARNING',STATE.boss.name,'BOSS SECTOR');SpaceAudio.bossEnter();haptic([30,30,50])}
function bossFan(count,speed,spread){if(!STATE.boss)return;var b=STATE.boss,base=Math.atan2(PLAYER.y-b.y,PLAYER.x-b.x);for(var i=0;i<count;i++){var a=base+(i-(count-1)/2)*spread;enemyBullets.push({type:'orb',x:b.x,y:b.y+25,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:6,t:0})}}
function bossRing(count,speed){if(!STATE.boss)return;var b=STATE.boss;for(var i=0;i<count;i++){var a=i*TAU/count+b.t*.25;enemyBullets.push({type:'orb',x:b.x,y:b.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:5,t:0})}}
function bossLaser(){var x=45+Math.random()*(STATE.w-90);warnings.push({type:'laser',x:x,width:46,t:0,delay:1.15,active:.55,hit:false});floatingText(x,STATE.h*.45,'DANGER','#ff5e88',.8);SpaceAudio.bossHit()}
function activatePower(type,x,y){if(type==='shield'){STATE.shield=Math.max(STATE.shield,9);toast('AEGIS SHIELD ONLINE');SpaceAudio.shield()}else if(type==='slow'){STATE.slow=6.5;toast('TIME DILATION');SpaceAudio.level()}else if(type==='magnet'){STATE.magnet=8;toast('GRAVITY SURGE');SpaceAudio.collect(3,STATE.combo)}else if(type==='heal'){STATE.energy=Math.min(STATE.maxEnergy,STATE.energy+45);toast('REACTOR RESTORED');SpaceAudio.level()}else if(type==='overdrive'){STATE.overdrive=7;toast('FLOW OVERDRIVE');SpaceAudio.level()}else{STATE.nova=Math.min(STATE.novaMax,STATE.nova+55);toast('NOVA CHARGE +55%');SpaceAudio.collect(3,STATE.combo)}shockwave(x,y,powerColor(type),20,180);haptic(14)}
function powerColor(type){return type==='shield'?'#42f5ff':type==='slow'?'#ff4fd8':type==='magnet'?'#ffe66d':type==='heal'?'#79ff91':type==='overdrive'?'#9b7bff':'#ffffff'}
function burst(x,y,color,count,force){for(var i=0;i<count;i++){var a=Math.random()*TAU,s=(55+Math.random()*215)*(force||1);particles.push({x:x,y:y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.62,max:.92,size:1.2+Math.random()*4,color:color,drag:.035+Math.random()*.05})}}
function shockwave(x,y,color,start,end){shockwaves.push({x:x,y:y,r:start||8,end:end||120,life:.52,max:.52,color:color})}
function floatingText(x,y,text,color,scale){floating.push({x:x,y:y,text:text,color:color||'#fff',life:.82,max:.82,vy:-36,scale:scale||1})}
function playerRadius(){return PLAYER.r*STATE.mods.hitbox}
function rectHit(o){var r=playerRadius(),dx=Math.abs(PLAYER.x-o.x),dy=Math.abs(PLAYER.y-o.y);return dx<o.w/2+r&&dy<o.h/2+r}
function circleHit(a,b,padding){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+(padding||0)}
function nearMiss(o){o.near=true;STATE.combo=Math.min(30,STATE.combo+1);STATE.maxCombo=Math.max(STATE.maxCombo,STATE.combo);STATE.stats.near++;STATE.comboTimer=2.25+STATE.mods.comboGrace;STATE.multiplier=Math.min(8,1+(STATE.upgrades.overdrive||0)*.35+Math.floor(STATE.combo/2)*.22+(STATE.overdrive>0?.7:0));var bonus=35+STATE.combo*9;addScore(bonus,'NEAR MISS',o.x,PLAYER.y-38);runXpGain(5+Math.min(8,STATE.combo));STATE.nova=Math.min(100,STATE.nova+(7+STATE.combo*.55)*STATE.mods.novaRate);updateContract('near',1);addDaily('near',1);SpaceAudio.near(STATE.combo);haptic(5);STATE.chromatic=Math.min(1,STATE.chromatic+.24);if(STATE.combo===5||STATE.combo===10||STATE.combo===15||STATE.combo===20){waveBanner('FLOW CHAIN','x'+STATE.multiplier.toFixed(1),'COMBO '+STATE.combo);SpaceAudio.level()}}
function damagePlayer(sourceX,sourceY){if(STATE.invuln>0||STATE.mode!=='playing')return;if(STATE.shield>0){STATE.shield=0;STATE.invuln=.75;STATE.shake=11;STATE.flash=.42;burst(sourceX||PLAYER.x,sourceY||PLAYER.y,'#42f5ff',28,1.1);shockwave(PLAYER.x,PLAYER.y,'#42f5ff',18,115);toast('SHIELD FRACTURED');SpaceAudio.shieldBreak();haptic([18,25,18]);return}STATE.lives--;STATE.stats.damageTaken++;STATE.invuln=1.5;STATE.hitStop=.07;STATE.shake=17;STATE.flash=.75;STATE.energy=Math.max(25,STATE.energy-25);STATE.combo=0;STATE.multiplier=1+(STATE.upgrades.overdrive||0)*.35;burst(PLAYER.x,PLAYER.y,'#ff4fd8',34,1.35);shockwave(PLAYER.x,PLAYER.y,'#ff4fd8',12,150);SpaceAudio.hit();haptic([30,35,55]);if(STATE.lives<=0){if(STATE.mods.revive){STATE.mods.revive=false;STATE.lives=1;STATE.energy=Math.max(STATE.maxEnergy*.55,45);STATE.shield=5;waveBanner('QUANTUM RETURN','REVIVED','ONE MORE CHANCE');SpaceAudio.level()}else{endRun(true);return}}else toast('PULSE FRACTURED • '+STATE.lives+' LIVES LEFT');syncRunUI()}
function activateNova(){if(STATE.mode!=='playing'||STATE.nova<STATE.novaMax)return;STATE.nova=0;STATE.novaUses++;STATE.hitStop=.12;STATE.shake=20;STATE.flash=1;STATE.chromatic=1;STATE.invuln=1.05;burst(PLAYER.x,PLAYER.y,skinColor(),75,1.65);shockwave(PLAYER.x,PLAYER.y,'#ffe66d',18,STATE.w*.95);obstacles=[];enemyBullets=[];warnings=[];if(STATE.boss){var damage=55+STATE.runLevel*3+STATE.mods.damage*8;STATE.boss.hp-=damage;floatingText(STATE.boss.x,STATE.boss.y+55,'NOVA -'+Math.floor(damage),'#ffe66d',1.25)}addScore(400,'NOVA',PLAYER.x,PLAYER.y-72);runXpGain(25);updateContract('nova',1);SpaceAudio.nova();haptic([25,18,60])}
function skinColor(){return SKINS[META.skin]?SKINS[META.skin].color:'#42f5ff'}
function completeWave(){if(STATE.transition||STATE.boss)return;STATE.transition=true;STATE.stats.waves++;updateContract('wave',1);runXpGain(35+STATE.wave*4);var bonus=220+STATE.wave*75;addScore(bonus,'WAVE CLEAR',PLAYER.x,PLAYER.y-70);addRunCredits(3+Math.floor(STATE.wave/2),PLAYER.x,PLAYER.y-95);STATE.energy=Math.min(STATE.maxEnergy,STATE.energy+28);if(STATE.mods.shieldStart>0)STATE.shield=Math.max(STATE.shield,4+STATE.mods.shieldStart*2);STATE.wave++;STATE.waveClock=0;STATE.contract=randomContract();STATE.contractProgress=0;STATE.contractDone=false;updateContractUI();obstacles=[];enemyBullets=[];warnings=[];SpaceAudio.wave();haptic([12,22,35]);var bossWave=STATE.wave%4===0;if(bossWave){STATE.bossPending=true;waveBanner('RIFT DETECTED','WAVE '+STATE.wave,'BOSS INCOMING')}else waveBanner('SECTOR CLEAR','WAVE '+STATE.wave,'+'+bonus+' CLEAR BONUS');setTimeout(function(){STATE.transition=false;if(STATE.bossPending&&STATE.mode==='playing')spawnBoss()},1250)}
function firePlayerBullet(){if(!STATE.boss)return;var crit=Math.random()<STATE.mods.critical,damage=(8+STATE.runLevel*.5)*STATE.mods.damage*(crit?2.2:1);playerBullets.push({x:PLAYER.x,y:PLAYER.y-18,vx:0,vy:-690,r:crit?5:3.8,damage:damage,crit:crit,life:2})}
function bossDefeated(){var b=STATE.boss;if(!b)return;STATE.boss=null;STATE.bosses++;STATE.bossRewardPending=true;STATE.transition=true;STATE.stats.waves++;updateContract('wave',1);STATE.wave++;STATE.waveClock=0;STATE.contract=randomContract();STATE.contractProgress=0;STATE.contractDone=false;updateContractUI();STATE.hitStop=.2;STATE.shake=24;STATE.flash=1;STATE.chromatic=1;enemyBullets=[];warnings=[];burst(b.x,b.y,'#ff4fd8',90,1.85);burst(b.x,b.y,'#ffe66d',60,1.4);shockwave(b.x,b.y,'#ffe66d',30,STATE.w*.9);addScore(2200+STATE.wave*180,'BOSS DOWN',b.x,b.y+70);addRunCredits(35+STATE.wave*2,b.x,b.y+95);runXpGain(80+STATE.wave*8);addDaily('boss',1);UI.bossBar.classList.remove('show');SpaceAudio.bossDown();haptic([25,20,25,20,80]);waveBanner('SENTINEL DESTROYED','COSMIC CACHE','RARE RELIC AVAILABLE');setTimeout(function(){if(STATE.mode==='playing')openUpgrade(true)},1450)}
function updateBoss(dt){var b=STATE.boss;if(!b)return;b.t+=dt;var ratio=b.hp/b.maxHp,newPhase=ratio>.66?1:ratio>.32?2:3;if(newPhase!==b.phase){b.phase=newPhase;UI.bossPhase.textContent='PHASE '+['I','II','III'][newPhase-1];waveBanner('BOSS EVOLVED','PHASE '+['I','II','III'][newPhase-1],newPhase===3?'FINAL ASSAULT':'PATTERN SHIFT');SpaceAudio.bossEnter();STATE.shake=12}if(b.y<b.targetY){b.y+=125*dt;return}b.entering=false;b.x=STATE.w/2+Math.sin(b.t*(.72+b.phase*.1))*Math.min(STATE.w*.31,145);b.shotTimer-=dt;b.patternTimer-=dt;if(b.shotTimer<=0){if(b.phase===1)bossFan(3,205,.18);else if(b.phase===2)bossFan(5,225,.15);else bossFan(7,250,.13);b.shotTimer=Math.max(.48,1.08-b.phase*.16-STATE.wave*.012)}if(b.patternTimer<=0){if(b.phase===1)bossRing(8,150);else if(b.phase===2){bossRing(12,175);bossLaser()}else{bossRing(16,195);bossLaser();setTimeout(function(){if(STATE.boss&&STATE.mode==='playing')bossLaser()},520)}b.patternTimer=Math.max(1.9,3.5-b.phase*.4)}STATE.playerShotTimer-=dt;if(STATE.playerShotTimer<=0){firePlayerBullet();STATE.playerShotTimer=Math.max(.075,.19/STATE.mods.fireRate)}UI.bossFill.style.transform='scaleX('+Math.max(0,b.hp/b.maxHp)+')';if(b.hp<=0)bossDefeated()}
function updateWarnings(dt){for(var i=warnings.length-1;i>=0;i--){var w=warnings[i];w.t+=dt;if(w.t>w.delay&&w.t<w.delay+w.active&&!w.hit&&Math.abs(PLAYER.x-w.x)<w.width/2+playerRadius()){w.hit=true;damagePlayer(w.x,PLAYER.y)}if(w.t>w.delay+w.active+.25)warnings.splice(i,1)}}
function updateGame(dt){if(STATE.hitStop>0){STATE.hitStop-=dt;updateParticles(dt*.15);return}var timeScale=STATE.slow>0?.58:1,scaled=dt*timeScale,worldSpeed=(295+Math.min(320,STATE.time*4.4)+STATE.wave*8)*timeScale;STATE.time+=dt;STATE.waveClock+=STATE.boss?0:dt;STATE.energy=Math.min(STATE.maxEnergy,STATE.energy-dt*(2.25+Math.min(2.1,STATE.time/40))*STATE.mods.energyDrain+STATE.mods.regen*dt);STATE.shield=Math.max(0,STATE.shield-dt);STATE.slow=Math.max(0,STATE.slow-dt);STATE.magnet=Math.max(0,STATE.magnet-dt);STATE.overdrive=Math.max(0,STATE.overdrive-dt);STATE.invuln=Math.max(0,STATE.invuln-dt);STATE.shake=Math.max(0,STATE.shake-dt*30);STATE.flash=Math.max(0,STATE.flash-dt*(META.settings.reducedFlash?6:3.6));STATE.chromatic=Math.max(0,STATE.chromatic-dt*2.6);STATE.nova=Math.min(100,STATE.nova+dt*(1.65+STATE.combo*.035)*STATE.mods.novaRate);if(STATE.energy<=0){STATE.energy=0;damagePlayer(PLAYER.x,PLAYER.y);if(STATE.mode!=='playing')return;STATE.energy=Math.max(32,STATE.maxEnergy*.32)}if(STATE.combo>0){STATE.comboTimer-=dt;if(STATE.comboTimer<=0){STATE.combo=Math.max(0,STATE.combo-1);STATE.comboTimer=STATE.combo?(.34+STATE.mods.comboGrace*.18):0;STATE.multiplier=Math.min(8,1+(STATE.upgrades.overdrive||0)*.35+Math.floor(STATE.combo/2)*.22+(STATE.overdrive>0?.7:0))}}if(STATE.contract&&STATE.contract.type==='survive')updateContract('survive',dt);PLAYER.tilt+=(PLAYER.targetX-PLAYER.x)*dt*.02;PLAYER.tilt*=Math.pow(.02,dt);PLAYER.x+=(PLAYER.targetX-PLAYER.x)*(1-Math.pow(.00055,dt));PLAYER.y=STATE.h*.79;PLAYER.trail.unshift({x:PLAYER.x,y:PLAYER.y,life:1});if(PLAYER.trail.length>24)PLAYER.trail.pop();for(var tr=0;tr<PLAYER.trail.length;tr++)PLAYER.trail[tr].life-=dt*2.1;var intensity=Math.min(1,(STATE.wave-1)/10+STATE.combo/20+(STATE.boss?.25:0));SpaceAudio.tick(intensity,!!STATE.boss,STATE.combo);for(var s=0;s<backgroundStars.length;s++){var star=backgroundStars[s];star.tw+=dt*(.5+star.z);star.y+=worldSpeed*star.z*(.34+STATE.combo*.006)*dt;if(star.y>STATE.h+5){star.y=-5;star.x=Math.random()*STATE.w}}if(!STATE.boss&&!STATE.bossPending&&!STATE.transition){STATE.spawnTimer-=scaled;if(STATE.spawnTimer<=0){if(STATE.wave>=3&&Math.random()<.1+STATE.wave*.008)spawnGate();else spawnObstacle();STATE.spawnTimer=Math.max(.22,.7-STATE.time*.0035-STATE.wave*.014)*(.78+Math.random()*.42)}}STATE.coreTimer-=scaled;if(STATE.coreTimer<=0){if(Math.random()<.12+STATE.mods.luck*.04)spawnCoreTrail();else spawnCore();STATE.coreTimer=.66+Math.random()*.62}STATE.powerTimer-=scaled;if(STATE.powerTimer<=0){spawnPower();STATE.powerTimer=Math.max(5.8,9.5-STATE.mods.luck*1.2)+Math.random()*4.5}updateObstacles(scaled,worldSpeed);updateCores(scaled,worldSpeed);updatePowers(scaled,worldSpeed);updateBoss(dt);updateBullets(dt);updateWarnings(dt);updateParticles(dt);if(!STATE.boss&&!STATE.bossPending&&!STATE.transition&&STATE.waveClock>=STATE.waveDuration)completeWave();syncRunUI()}
function updateObstacles(dt,speed){for(var i=obstacles.length-1;i>=0;i--){var o=obstacles[i];o.t+=dt;o.y+=speed*dt;o.a+=o.spin*dt;if(o.type==='seeker')o.x+=(PLAYER.x-o.x)*dt*(.58+STATE.wave*.015);else o.x+=o.vx*dt;if(o.type==='mine'&&!o.exploded&&o.y>=o.triggerY){o.exploded=true;for(var n=0;n<8;n++){var a=n*TAU/8;enemyBullets.push({type:'mine',x:o.x,y:o.y,vx:Math.cos(a)*150,vy:Math.sin(a)*150,r:5,t:0})}burst(o.x,o.y,'#ff4fd8',18,.8);obstacles.splice(i,1);continue}if(!o.near&&o.y>PLAYER.y+o.h*.45){var margin=Math.abs(o.x-PLAYER.x)-(o.w/2+playerRadius());if(margin>0&&margin<44)nearMiss(o)}if(STATE.invuln<=0&&rectHit(o)){obstacles.splice(i,1);damagePlayer(o.x,o.y);if(STATE.mode!=='playing')return;continue}if(o.y-o.h>STATE.h+55||o.x<-o.w||o.x>STATE.w+o.w)obstacles.splice(i,1)}}
function updateCores(dt,speed){for(var i=cores.length-1;i>=0;i--){var c=cores[i];c.y+=speed*.87*dt;c.t+=dt*4.6;var range=STATE.mods.magnet+(STATE.magnet>0?180:0);if(range){var dx=PLAYER.x-c.x,dy=PLAYER.y-c.y,d=Math.hypot(dx,dy);if(d<range){var pull=2.4+STATE.mods.magnet/120;c.x+=dx*dt*pull;c.y+=dy*dt*pull}}if(Math.hypot(PLAYER.x-c.x,PLAYER.y-c.y)<playerRadius()+c.r+6){var yieldMult=STATE.mods.coreValue,energyGain=9*c.value*yieldMult,xpGain=(7*c.value+2)*yieldMult;STATE.cores+=c.value;STATE.energy=Math.min(STATE.maxEnergy,STATE.energy+energyGain);STATE.nova=Math.min(100,STATE.nova+5*c.value*STATE.mods.novaRate);addScore(52*c.value,'CORE',c.x,c.y);runXpGain(xpGain);if(c.credit)addRunCredits(c.credit,c.x,c.y-28);updateContract('cores',c.value);addDaily('cores',c.value);burst(c.x,c.y,c.golden?'#ffe66d':skinColor(),14+c.value*3,.72);shockwave(c.x,c.y,c.golden?'#ffe66d':skinColor(),5,50);SpaceAudio.collect(c.value,STATE.combo);haptic(6);cores.splice(i,1);continue}if(c.y>STATE.h+35)cores.splice(i,1)}}
function updatePowers(dt,speed){for(var i=powers.length-1;i>=0;i--){var p=powers[i];p.y+=speed*.79*dt;p.t+=dt*3;if(Math.hypot(PLAYER.x-p.x,PLAYER.y-p.y)<playerRadius()+p.r+7){activatePower(p.type,p.x,p.y);addScore(120,'POWER',p.x,p.y-28);runXpGain(14);burst(p.x,p.y,powerColor(p.type),24,.85);powers.splice(i,1);continue}if(p.y>STATE.h+35)powers.splice(i,1)}}
function updateBullets(dt){for(var i=playerBullets.length-1;i>=0;i--){var p=playerBullets[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(STATE.boss&&Math.hypot(p.x-STATE.boss.x,p.y-STATE.boss.y)<STATE.boss.r+p.r){STATE.boss.hp-=p.damage;SpaceAudio.bossHit();if(p.crit)floatingText(p.x,p.y,'CRIT '+Math.floor(p.damage),'#ffe66d',.7);burst(p.x,p.y,p.crit?'#ffe66d':skinColor(),p.crit?7:3,.25);playerBullets.splice(i,1);continue}if(p.y<-25||p.life<=0)playerBullets.splice(i,1)}for(i=enemyBullets.length-1;i>=0;i--){var e=enemyBullets[i];e.x+=e.vx*dt;e.y+=e.vy*dt;e.t+=dt;if(STATE.invuln<=0&&Math.hypot(PLAYER.x-e.x,PLAYER.y-e.y)<playerRadius()+e.r){enemyBullets.splice(i,1);damagePlayer(e.x,e.y);if(STATE.mode!=='playing')return;continue}if(e.x<-35||e.x>STATE.w+35||e.y<-50||e.y>STATE.h+40)enemyBullets.splice(i,1)}}
function updateParticles(dt){for(var i=particles.length-1;i>=0;i--){var p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(p.drag||.04,dt);p.vy*=Math.pow(p.drag||.04,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1)}for(i=floating.length-1;i>=0;i--){var f=floating[i];f.y+=f.vy*dt;f.life-=dt;if(f.life<=0)floating.splice(i,1)}for(i=shockwaves.length-1;i>=0;i--){var sw=shockwaves[i];sw.life-=dt;sw.r+=(sw.end-sw.r)*dt*6;if(sw.life<=0)shockwaves.splice(i,1)}}
