function spawnObstacle(){var diff=Math.min(1.6,S.time/70),roll=Math.random(),type=roll<.48?'shard':roll<.68?'bar':roll<.84?'seeker':'spinner',size=22+Math.random()*(26+diff*9),o={type:type,x:28+Math.random()*(S.w-56),y:-55,w:size,h:size,a:Math.random()*TAU,spin:(Math.random()-.5)*(1.2+diff),vx:(Math.random()-.5)*25,near:false,t:0};if(type==='bar'){o.w=Math.min(80+Math.random()*100,S.w*.48);o.h=16+Math.random()*11;o.spin=0}if(type==='seeker'){o.w=o.h=25;o.vx=0}if(type==='spinner'){o.w=o.h=38;o.spin=2.5+diff}obstacles.push(o)}
function spawnCore(){cores.push({x:26+Math.random()*(S.w-52),y:-25,r:8,t:Math.random()*TAU,value:Math.random()<.1?3:1})}
function spawnPower(){var types=['shield','slow','magnet','heal'],type=types[Math.floor(Math.random()*types.length)];powers.push({x:34+Math.random()*(S.w-68),y:-30,r:13,t:0,type:type})}
function spawnBoss(){S.bossPending=false;S.boss={x:S.w/2,y:-100,targetY:125,r:56,hp:110+S.wave*28,maxHp:110+S.wave*28,t:0,shot:1.1,phase:0};el.bossBar.classList.add('show');toast('VOID SENTINEL');tone(100,.6,'sawtooth',.06,80)}
function bossShoot(){if(!S.boss)return;var b=S.boss,count=b.hp<b.maxHp*.5?5:3;for(var i=0;i<count;i++){var a=Math.atan2(P.y-b.y,P.x-b.x)+(i-(count-1)/2)*.18;enemyBullets.push({x:b.x,y:b.y+35,vx:Math.cos(a)*(180+S.wave*8),vy:Math.sin(a)*(180+S.wave*8),r:6})}}
function firePlayer(){if(!S.boss)return;bullets.push({x:P.x,y:P.y-16,vy:-620,r:4,damage:5+S.upgrade.score*.7})}
function nova(){if(S.mode!=='play'||S.nova<100)return;S.nova=0;S.shake=15;S.flash=.75;burst(P.x,P.y,'#ffe66d',60,1.5);obstacles=[];enemyBullets=[];if(S.boss)S.boss.hp-=35+S.upgrade.nova*8;S.score+=300*S.scoreMult;if(S.mission&&S.mission.type==='nova')S.mission.progress=1;toast('NOVA PULSE');tone(220,.45,'sawtooth',.08,700);buzz([25,20,45]);updateMissionUI()}
function activatePower(type){if(type==='shield'){S.shield=8;toast('SHIELD ONLINE')}else if(type==='slow'){S.slow=6;toast('TIME DILATION')}else if(type==='magnet'){S.magnet=8;toast('GRAVITY SURGE')}else{S.energy=Math.min(S.maxEnergy,S.energy+35);toast('CORE RESTORED')}tone(520,.18,'triangle',.055,260);buzz(12)}
function burst(px,py,color,count,force){for(var i=0;i<count;i++){var a=Math.random()*TAU,sp=(55+Math.random()*210)*(force||1);particles.push({x:px,y:py,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.35+Math.random()*.5,max:.85,size:1.5+Math.random()*3.5,color:color})}}
function rectHit(o){var r=P.r*(1-S.upgrade.hitbox*.11),dx=Math.abs(P.x-o.x),dy=Math.abs(P.y-o.y);return dx<o.w/2+r&&dy<o.h/2+r}
function circleHit(a,b,extra){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+(extra||0)}
function missionProgress(){return S.mission?Math.min(S.mission.goal,S.mission.progress||0):0}
function update(dt){var slow=S.slow>0?.58:1,speed=(285+Math.min(300,S.time*4.6))*slow;S.time+=dt;S.waveTime+=dt;if(S.mission&&S.mission.type==='survive'&&!S.missionDone)S.mission.progress=(S.mission.progress||0)+dt;S.score+=dt*(10+S.time*.16)*S.scoreMult;S.energy=Math.min(S.maxEnergy,S.energy-dt*(2.35+Math.min(2.2,S.time/35))+S.regen*dt);if(S.energy<=0){S.energy=0;loseLife();S.energy=Math.max(35,S.maxEnergy*.35)}S.shield=Math.max(0,S.shield-dt);S.slow=Math.max(0,S.slow-dt);S.magnet=Math.max(0,S.magnet-dt);S.invuln=Math.max(0,S.invuln-dt);S.comboTime-=dt;if(S.comboTime<=0)S.combo=Math.max(0,S.combo-1);S.shake=Math.max(0,S.shake-dt*28);S.flash=Math.max(0,S.flash-dt*3.2);S.nova=Math.min(100,S.nova+dt*(1.65+S.upgrade.nova*.38));
P.x+=(P.target-P.x)*(1-Math.pow(.0005,dt));P.trail.unshift({x:P.x,y:P.y,life:1});if(P.trail.length>20)P.trail.pop();for(var t=0;t<P.trail.length;t++)P.trail[t].life-=dt*2.2;
if(S.bossPending&&!S.boss)spawnBoss();if(!S.boss){S.spawn-=dt;if(S.spawn<=0){spawnObstacle();S.spawn=Math.max(.24,.7-S.time*.0048)*(.78+Math.random()*.44)}}S.coreSpawn-=dt;if(S.coreSpawn<=0){spawnCore();S.coreSpawn=.65+Math.random()*.62}S.powerSpawn-=dt;if(S.powerSpawn<=0){spawnPower();S.powerSpawn=8+Math.random()*6}
for(var i=0;i<stars.length;i++){stars[i].y+=speed*stars[i].z*.38*dt;if(stars[i].y>S.h+4){stars[i].y=-4;stars[i].x=Math.random()*S.w}}
for(i=obstacles.length-1;i>=0;i--){var o=obstacles[i];o.t+=dt;o.y+=speed*dt;o.a+=o.spin*dt;if(o.type==='seeker')o.x+=(P.x-o.x)*dt*.7;else o.x+=o.vx*dt;if(!o.near&&o.y>P.y&&Math.abs(o.x-P.x)<o.w/2+45){o.near=true;S.combo=Math.min(12,S.combo+1);S.comboTime=2;S.score+=25*S.combo*S.scoreMult;S.nova=Math.min(100,S.nova+6);if(S.mission&&S.mission.type==='near'&&!S.missionDone)S.mission.progress=(S.mission.progress||0)+1;tone(250+S.combo*15,.04,'triangle',.02,50)}if(S.invuln<=0&&rectHit(o)){if(S.shield>0){S.shield=0;S.invuln=.7;burst(o.x,o.y,'#42f5ff',22,1);obstacles.splice(i,1);toast('SHIELD BROKEN');continue}else{obstacles.splice(i,1);loseLife();if(S.mode==='over')return}}if(o.y-o.h>S.h+55)obstacles.splice(i,1)}
for(i=cores.length-1;i>=0;i--){var c=cores[i];c.y+=speed*.88*dt;c.t+=dt*4.5;var magnetActive=S.magnet>0||S.upgrade.magnet>0,range=magnetActive?140+S.upgrade.magnet*45:0;if(range){var dx=P.x-c.x,dy=P.y-c.y,d=Math.hypot(dx,dy);if(d<range){c.x+=dx*dt*(2.3+S.upgrade.magnet*.5);c.y+=dy*dt*(2.3+S.upgrade.magnet*.5)}}if(circleHit(P,c,5)){S.cores+=c.value;if(S.mission&&S.mission.type==='cores'&&!S.missionDone)S.mission.progress=(S.mission.progress||0)+c.value;S.energy=Math.min(S.maxEnergy,S.energy+9*c.value);S.score+=45*c.value*S.scoreMult;S.runCredits+=c.value;S.nova=Math.min(100,S.nova+5*c.value);burst(c.x,c.y,c.value===3?'#ffe66d':'#42f5ff',12+c.value*3,.7);tone(c.value===3?760:620,.07,'sine',.04,150);cores.splice(i,1);updateMissionUI();continue}if(c.y>S.h+30)cores.splice(i,1)}
for(i=powers.length-1;i>=0;i--){var pw=powers[i];pw.y+=speed*.82*dt;pw.t+=dt*3;if(circleHit(P,pw,6)){activatePower(pw.type);burst(pw.x,pw.y,powerColor(pw.type),22,.8);powers.splice(i,1);continue}if(pw.y>S.h+30)powers.splice(i,1)}
if(S.boss){var b=S.boss;b.t+=dt;if(b.y<b.targetY)b.y+=120*dt;else{b.x=S.w/2+Math.sin(b.t*.9)*Math.min(S.w*.32,150);b.shot-=dt;if(b.shot<=0){bossShoot();b.shot=Math.max(.55,1.25-S.wave*.05)}}S.bulletSpawn-=dt;if(S.bulletSpawn<=0){firePlayer();S.bulletSpawn=.13}el.bossFill.style.transform='scaleX('+Math.max(0,b.hp/b.maxHp)+')';if(b.hp<=0){S.score+=1500*S.scoreMult;S.runCredits+=35;burst(b.x,b.y,'#ff4fd8',75,1.7);tone(130,.65,'sawtooth',.08,800);toast('SENTINEL DESTROYED +35');S.boss=null;el.bossBar.classList.remove('show');S.waveTime=S.waveLength-1}}
for(i=bullets.length-1;i>=0;i--){var bl=bullets[i];bl.y+=bl.vy*dt;if(S.boss&&Math.hypot(bl.x-S.boss.x,bl.y-S.boss.y)<S.boss.r+bl.r){S.boss.hp-=bl.damage;burst(bl.x,bl.y,'#42f5ff',4,.3);bullets.splice(i,1);continue}if(bl.y<-20)bullets.splice(i,1)}
for(i=enemyBullets.length-1;i>=0;i--){var eb=enemyBullets[i];eb.x+=eb.vx*dt;eb.y+=eb.vy*dt;if(S.invuln<=0&&circleHit(P,eb,1)){enemyBullets.splice(i,1);if(S.shield>0){S.shield=0;toast('SHIELD BROKEN')}else loseLife();if(S.mode==='over')return;continue}if(eb.x<-30||eb.x>S.w+30||eb.y>S.h+30)enemyBullets.splice(i,1)}
for(i=particles.length-1;i>=0;i--){var p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.04,dt);p.vy*=Math.pow(.04,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1)}
updateMissionUI();if(!S.boss&&!S.bossPending&&S.waveTime>=S.waveLength)nextWave();syncHud()}
function syncHud(){el.score.textContent=Math.floor(S.score).toLocaleString();el.energy.style.transform='scaleX('+Math.max(0,S.energy/S.maxEnergy)+')';el.wave.textContent=S.wave;el.lives.textContent='●'.repeat(Math.max(0,S.lives));el.pulseValue.textContent=Math.floor(S.nova)+'%';el.pulse.classList.toggle('ready',S.nova>=100)}
function powerColor(type){return type==='shield'?'#42f5ff':type==='slow'?'#ff4fd8':type==='magnet'?'#ffe66d':'#79ff91'}