(function(){
'use strict';
var A={ctx:null,master:null,music:null,sfx:null,filter:null,started:false,nextBeat:0,nextPad:0,step:0,settings:null,intensity:0,pads:[]};
function init(settings){A.settings=settings;if(A.started){resume();setSettings(settings);return}var C=window.AudioContext||window.webkitAudioContext;if(!C)return;A.ctx=new C();A.master=A.ctx.createGain();A.music=A.ctx.createGain();A.sfx=A.ctx.createGain();A.filter=A.ctx.createBiquadFilter();A.filter.type='lowpass';A.filter.frequency.value=1300;A.filter.Q.value=.8;A.music.connect(A.filter).connect(A.master);A.sfx.connect(A.master);A.master.connect(A.ctx.destination);A.master.gain.value=.82;A.music.gain.value=settings.music?.28:0;A.sfx.gain.value=settings.sfx?.78:0;startAtmosphere();A.nextBeat=A.ctx.currentTime+.08;A.nextPad=A.ctx.currentTime+.4;A.started=true}
function resume(){if(A.ctx&&A.ctx.state==='suspended')A.ctx.resume()}
function setSettings(settings){A.settings=settings;if(!A.started)return;A.music.gain.setTargetAtTime(settings.music?.28:0,A.ctx.currentTime,.1);A.sfx.gain.setTargetAtTime(settings.sfx?.78:0,A.ctx.currentTime,.1)}
function startAtmosphere(){var freqs=[41.2,55,82.41,110];freqs.forEach(function(f,i){var o=A.ctx.createOscillator(),g=A.ctx.createGain(),p=A.ctx.createStereoPanner?A.ctx.createStereoPanner():null;o.type=i<2?'sine':'triangle';o.frequency.value=f;g.gain.value=i===0?.04:i===1?.028:.011;if(p){p.pan.value=i===2?-.5:i===3?.5:0;o.connect(g).connect(p).connect(A.music)}else o.connect(g).connect(A.music);o.start();A.pads.push({o:o,g:g})});var lfo=A.ctx.createOscillator(),lg=A.ctx.createGain();lfo.frequency.value=.045;lg.gain.value=520;lfo.connect(lg).connect(A.filter.frequency);lfo.start();var len=A.ctx.sampleRate*2,buf=A.ctx.createBuffer(1,len,A.ctx.sampleRate),d=buf.getChannelData(0);for(var i=0;i<len;i++)d[i]=(Math.random()*2-1)*.22;var src=A.ctx.createBufferSource(),f=A.ctx.createBiquadFilter(),g=A.ctx.createGain();src.buffer=buf;src.loop=true;f.type='lowpass';f.frequency.value=420;g.gain.value=.03;src.connect(f).connect(g).connect(A.music);src.start()}
function tone(freq,dur,type,vol,slide,pan,target){if(!A.started)return;var out=target||A.sfx;if(out===A.sfx&&!A.settings.sfx)return;if(out===A.music&&!A.settings.music)return;var now=A.ctx.currentTime,o=A.ctx.createOscillator(),g=A.ctx.createGain(),p=A.ctx.createStereoPanner?A.ctx.createStereoPanner():null;o.type=type||'sine';o.frequency.setValueAtTime(Math.max(20,freq),now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(vol||.04,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+dur);if(p){p.pan.value=pan||0;o.connect(g).connect(p).connect(out)}else o.connect(g).connect(out);o.start(now);o.stop(now+dur+.03)}
function noise(dur,vol,cutoff){if(!A.started||!A.settings.sfx)return;var len=Math.max(1,Math.floor(A.ctx.sampleRate*dur)),buf=A.ctx.createBuffer(1,len,A.ctx.sampleRate),d=buf.getChannelData(0);for(var i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);var src=A.ctx.createBufferSource(),f=A.ctx.createBiquadFilter(),g=A.ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=cutoff||900;g.gain.setValueAtTime(vol||.05,A.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,A.ctx.currentTime+dur);src.connect(f).connect(g).connect(A.sfx);src.start();src.stop(A.ctx.currentTime+dur)}
function chord(root,minor,dur,vol,target){var ratios=minor?[1,1.1892,1.4983]:[1,1.2599,1.4983];ratios.forEach(function(r,i){setTimeout(function(){tone(root*r,dur,'sine',(vol||.035)/(i+1),root*r*.05,(i-1)*.25,target)},i*35)})}
function tick(intensity,boss,combo){if(!A.started||!A.settings.music)return;resume();A.intensity=intensity||0;var now=A.ctx.currentTime,rate=boss?.24:Math.max(.31,.66-A.intensity*.24);if(now>=A.nextBeat){A.nextBeat=now+rate;var scale=boss?[0,1,5,7,10,12,13,17]:[0,3,7,10,12,15,19,22],root=boss?46.25:65.41,idx=(A.step+(combo>6?2:0))%scale.length,f=root*Math.pow(2,scale[idx]/12);tone(f,rate*.88,boss?'sawtooth':'triangle',boss?.035:.021+A.intensity*.015,0,Math.sin(A.step*.78)*.62,A.music);if(A.step%4===0)tone(boss?34.65:32.7,.3,'sine',.035+A.intensity*.018,0,0,A.music);if(combo>=8&&A.step%2===0)tone(f*2,.18,'sine',.014,70,-.35,A.music);A.filter.frequency.setTargetAtTime(850+A.intensity*1900+(boss?550:0),now,.09);A.step++}
if(now>=A.nextPad){A.nextPad=now+(boss?5.5:7.5);var roots=boss?[55,61.74,46.25]:[110,98,130.81,82.41],r=roots[(A.step>>2)%roots.length];chord(r,boss,3.8,boss?.025:.019,A.music);if(!boss)tone(r*4,1.9,'sine',.008,180,.6,A.music)}}
A.init=init;A.resume=resume;A.setSettings=setSettings;A.tick=tick;A.ui=function(){tone(430,.07,'sine',.032,110)};A.collect=function(value,combo){tone(value>1?820:600+Math.min(combo,12)*18,.085,'sine',.052,190);if(value>1)tone(1210,.11,'triangle',.03,120,.35)};A.near=function(combo){tone(235+combo*24,.055,'triangle',.036,95,combo%2?-.5:.5)};A.hit=function(){noise(.22,.16,620);tone(165,.27,'sawtooth',.082,-105)};A.shield=function(){tone(510,.22,'sine',.06,420);tone(780,.16,'triangle',.03,-150)};A.shieldBreak=function(){noise(.19,.12,1450);tone(300,.22,'square',.052,-175)};A.nova=function(){noise(.58,.18,1900);tone(110,.72,'sawtooth',.1,1000);setTimeout(function(){chord(261.63,false,.55,.05,A.sfx)},110)};A.level=function(){chord(329.63,false,.46,.05,A.sfx);setTimeout(function(){tone(1174,.22,'sine',.04,240)},130)};A.wave=function(){chord(220,true,.42,.047,A.sfx);setTimeout(function(){chord(329.63,false,.48,.047,A.sfx)},170)};A.bossEnter=function(){noise(.75,.12,390);tone(46.25,1,'sawtooth',.085,28);setTimeout(function(){tone(92.5,.8,'sine',.045,-12)},160)};A.bossHit=function(){tone(120,.05,'square',.028,-15)};A.bossDown=function(){noise(1,.2,1200);tone(75,.95,'sawtooth',.105,900);setTimeout(function(){chord(220,false,.9,.065,A.sfx)},240)};A.achievement=function(){chord(392,false,.62,.06,A.sfx);setTimeout(function(){tone(1318,.3,'sine',.045,240)},150)};A.gameOver=function(){chord(110,true,1,.055,A.sfx);tone(170,.8,'sawtooth',.05,-120)};window.SpaceAudio=A;
})();
